// suppress inspection "SpellCheckingInspection" for whole file

= Changelog
Urs Joss <urs.joss@gmx.ch>
:icons: font
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
// Refs:
:url-repo: https://github.com/ursjoss/scipamato/
:url-issues: {url-repo}issues/
:url-tree: {url-repo}tree/
:url-cl: {url-repo}compare/

All notable changes to this project will be documented in this file.

== Format and Versioning Scheme

The format is based on https://keepachangelog.com/en/1.0.0/[Keep a Changelog].

SciPaMato is an application. Therefore, the versioning scheme is _not_ adhering
to https://semver.org/spec/v2.0.0.html[Semantic Versioning], which is mostly
targeting software components or libraries. Nevertheless, I'm sticking with
three part version numbers (e.g. 1.0.0), increasing the second number for
bigger changes and the third number for relatively small changes and bug fixes.
The first part of the version number will most likely remain version 1 for a
longer period of time and may only change with a major rewrite of parts or the
entire applicatin.

In the version prior to 1.0.0, the second digit indicated the the development
iteration, the third was keeping track of the number of the release within that
iteration. Given a version number 0.ITERATION.RELEASE, we were incrementing

. ITERATION version matching the project iteration
. RELEASE version with every release within the given iteration.

TIP: E.g. release 0.5.6 was the 6th release in iteration number 5.

NOTE: References to user stories are in the form Iteration/Story-Number.

////

[[v0.0.0]]
== [0.0.0] -- 2018-00-00

{url-cl}<prev>++...++main[Full Changelog]

.Added

.Changed

.Deprecated

.Removed

.Fixed

.Security

////


[[unreleased]]
== [unreleased]

{url-cl}2.1.11++...++main[Full Changelog]

.Added

////

.Changed

.Deprecated

.Removed

.Fixed

.Security

////


[[v2.1.11]]
== {url-tree}2.1.11[2.1.11] -- 2026-02-20

{url-cl}2.1.10++...++2.1.11[Full Changelog]

.Changed
- Bumped spring-boot, kotlin, feign,
  gradle, reckon, dependency-license-report,
  kotest, mockk, equalsverifier,
  github actions cache, checkout, docker/login-action, codeql-action, gradle/actions
- Fixed some typos in README and wiki-pages


[[v2.1.10]]
== {url-tree}2.1.10[2.1.10] -- 2026-01-21

{url-cl}2.1.9++...++2.1.10[Full Changelog]

.Changed
- Bumped kotlin, spring-boot, spring-cloud-starter-openfeign, spring-boot-admin-starter-client,
  wicket, wicketbootstrap, wicketstuff,
  kotest, mockk, equalverifier,
  gradle,lombok, sonarqube,
  cache, checkout, setup-java, upload-artifact,codeql-action

.Removed
- buildSrc
- modules common-test and commons-persistence-jooq-test


[[v2.1.9]]
== {url-tree}2.1.9[2.1.9] -- 2025-11-23

{url-cl}2.1.8++...++2.1.9[Full Changelog]

.Changed
- Bump sprint-boot, sprint-boot-admin-starter-client, lombok,
  gradle,
  kotest, equalsverifier,
  dependency-license-report, sonarqube,
  github actions checkout, code-ql, digest


[[v2.1.8]]
== {url-tree}2.1.8[2.1.8] -- 2025-10-28

{url-cl}2.1.7++...++2.1.8[Full Changelog]

.Changed
- Bump spring boot, kotlin, wicket, wicketbootstrap, wicketstuff, KRis,
  kotest, mockk, equalsverifier,
  lombok gradle plugin, jaxb gradle plugin, sonarqube gradle plugin,
  cache, gradle-actions, login-action, upload-artifact, codeql-action
- Migrated from FontAwesome6 to FontAwesome7 icons


[[v2.1.7]]
== {url-tree}2.1.7[2.1.7] -- 2025-09-18

{url-cl}2.1.6++...++2.1.7[Full Changelog]

.Changed
- Bumped spring-boot, wicket-spring-boot-starter, spring-boot-admin-starter-client,
  kotlin, guava, jasperreports, ehcache, wicket, wicketstuff, wicket-bootstrap,
  mockk, equalsverifier, gradle, lombok, sonarqube, reckon,
  cache, checkout, setup-java, docker-login, codeql-action, gradle-actions


[[v2.1.6]]
== {url-tree}2.1.6[2.1.6] -- 2025-06-23

{url-cl}2.1.5++...++2.1.6[Full Changelog]

.Changed
- {url-issues}911[#911] Search Order name to indicate excluded papers with an exclamation mark
- Bumped spring-boot, kotlin, mockk, equalsverifier,
  lombok plugin,
  codeql-action, gradle action


[[v2.1.5]]
== {url-tree}2.1.5[2.1.5] -- 2025-06-09

{url-cl}2.1.4++...++2.1.5[Full Changelog]

.Changed
- Bumped spring-boot, wicket, wicket-boostrap, wicketstuff,
  kotlin, kotlinx-coroutines,
  spring-cloud, feign, spring-boot-admin-starter-client, guava,
  gradle,
  mockk, equalsverifier,
  jaxb-gradle-plugin, lombok-gradle-plugin, sonarqube gradle plugin, reckon-gradle-plugin


[[v2.1.4]]
== {url-tree}2.1.4[2.1.4] -- 2025-03-21

{url-cl}2.1.3++...++2.1.4[Full Changelog]

.Changed
- reconfigured renovate to pin github action digists
- Bumped kotlin, spring-boot, guava, spring-cloud-starter-openfeign,
  equalsverifier,
  actions/cache, actions/upload-artifact, docker/login-action


[[v2.1.3]]
== {url-tree}2.1.3[2.1.3] -- 2025-03-13

{url-cl}2.1.2++...++2.1.3[Full Changelog]

.Changed
- Bumped lombok, spring-boot-admin-starter-client

.Fixed
- {url-issues}848[#848] Fix exporting papers to RIS format with very large pages indication


[[v2.1.2]]
== {url-tree}2.1.2[2.1.2] -- 2025-02-27

{url-cl}2.1.1++...++2.1.2[Full Changelog]

.Added
- {url-issues}843[#843] Add field "Statistical Method" to Review csv (and PDF) exports

.Changed
- Bumped spring-boot, kotlin, jOOQ, spring-boot-admin-starter-client, lombok, wicketstuff,
  detekt, mockk, equalsverifier,
  gradle


[[v2.1.1]]
== {url-tree}2.1.1[2.1.1] -- 2025-01-25

{url-cl}2.1.0++...++2.1.1[Full Changelog]

.Changed
- Bumped spring-boot, wicket, jOOQ, KRis, lombok,
  mockk, equalsverifier,
  gradle

- Removed debug logs for complex search


[[v2.1.0]]
== {url-tree}2.1.0[2.1.0] -- 2025-01-08

{url-cl}2.0.11++...++2.1.0[Full Changelog]

.Changed
- Bumped kotlin, coroutines, wicket-bootstrap, wicketstuff,
  mockk, equalsverifier,
  gradle


[[v2.0.11]]
== {url-tree}2.0.11[2.0.11] -- 2024-12-19

{url-cl}2.0.10++...++2.0.11[Full Changelog]

.Changed
- Bumped spring-boot, spring-dependency-management, wicket, jOOQ, KRis, guava


[[v2.0.10]]
== {url-tree}2.0.10[2.0.10] -- 2024-12-07

{url-cl}2.0.9++...++2.0.10[Full Changelog]

.Changed
- Bumped spring-boot, spring-cloud-starter-openfeign, spring-boot-admin-starter-client,
  lombok, jooq-gradle-plugin, reckon, sonarqube-plugin,
  equalsverifier


[[v2.0.9]]
== {url-tree}2.0.9[2.0.9] -- 2024-11-15

{url-cl}2.0.8++...++2.0.9[Full Changelog]

.Fixed
- reverted gradle update due to issue on server


[[v2.0.8]]
== {url-tree}2.0.8[2.0.8] -- 2024-11-15

{url-cl}2.0.7++...++2.0.8[Full Changelog]

.Changed
- Bumped spring-boot-admin-starter-client,
  gradle, jooq-gradle-plugin,
  equalsverifier

.Fixed
- avoid a null poiner exception


[[v2.0.7]]
== {url-tree}2.0.7[2.0.7] -- 2024-10-31

{url-cl}2.0.6++...++2.0.7[Full Changelog]

.Changed

.Fixed
- avoid a null poiner exception


[[v2.0.6]]
== {url-tree}2.0.6[2.0.6] -- 2024-10-29

{url-cl}2.0.5++...++2.0.6[Full Changelog]

.Changed
- bumped jooq-gradle-plugin

.Fixed
- {url-issues}727[#727] Open Help/Changelog in new browser window


[[v2.0.5]]
== {url-tree}2.0.5[2.0.5] -- 2024-10-24

{url-cl}2.0.4++...++2.0.5[Full Changelog]

.Changed
- bumped spring-boot, spring-boot-admin-starter-client,
  wicket, wicketbootstrap, wicketstuff,
  feign, guava, jasperreports,
  gradle, jooq-gradle-plugin, jaxb-gradle-plugin, lombok-gradle-plugin,
  mockk, equalsverifier


[[v2.0.4]]
== {url-tree}2.0.4[2.0.4] -- 2024-09-19

{url-cl}2.0.3++...++2.0.4[Full Changelog]

.Changed
- {url-issues}718[#718] Switch license plugin
- bumped spring-boot, kotlin, coroutines, gradle, jOOQ, guava, lombok,
  spring-cloud-starter-openfeign, feign-jaxb-jarkarta, kris, spring-boot-admin-starter-client,
  spring-dependency-management, jakarta.el-api,
  jnuit5, mockk, equalsverifier, sonarqube, detekt, dependency-license-report,
  docker/login-action gradle/actions
- migrated from gradle-build-action to gradle/actions/setup-gradle


[[v2.0.3]]
== {url-tree}2.0.3[2.0.3] -- 2024-06-20

{url-cl}2.0.2++...++2.0.3[Full Changelog]

.Changed
- {url-issues}712[#712] Use Optravis jooq-plugin instead of jooqModelator
- Bumped spring-boot, wicketstuff, feign

.Removed
- {url-issues}712[#712] Remove usage of jooqModelator gradle plugin


[[v2.0.2]]
== {url-tree}2.0.2[2.0.2] -- 2024-06-09

{url-cl}2.0.1++...++2.0.2[Full Changelog]

.Changed
- Bumped
  wicketbootstrap, wicketstuff,
  spring-boot-admin-starter-client,
  kotest

.Fixed
- {url-issues}701[#701] Fix deletion of attachments with very long names
- {url-issues}708[#708] Keep back-button hidden in public detail page after opening from search list


[[v2.0.1]]
== {url-tree}2.0.1[2.0.1] -- 2024-06-02

{url-cl}2.0.0++...++2.0.1[Full Changelog]

.Changed
- Bumped
  spring-boot, spring-dependency-management, spring-cloud-starter-openfeign, spring-boot-admin-starter-client,
  kotlin, kotlinx-coroutines, wicket
  jasperreports, jakarta.el-api, guava,
  kotest, mockk, equalsverifier,
  gradle,
  docker-login-action, wrapper-validation-action
- Refactored: Prepared for upcoming kotlin-2.0 migration

.Fixed
- Fix Tab Title to "Code"


[[v2.0.0]]
== {url-tree}2.0.0[2.0.0] -- 2024-03-28

{url-cl}1.10.3++...++2.0.0[Full Changelog]

.Changed
- {url-issues}669[#669] Bump Java version to 21
- {url-issues}657[#657] Bump major components (spring-boot-3.2, jOOQ 3.18, Flyway, wicket-10, spring-batch 5, jakarta, font-awesome 6)
- {url-issues}602[#602] Bump Wicket Stack
- Bumped
  spring-boot, kotlin, kotlinx-coroutines, wicket, wicketstuff, jOOQ, flyway, KRis, guava, lombok, spring-cloud-starter,
  gradle, KRis, detekt, sonarqube, openfeign, jasperreports,
  kotest, mockk, equalsverifier, testcontainers,


[[v1.10.3]]
== {url-tree}1.10.3[1.10.3] -- 2024-02-04

{url-cl}1.10.2++...++1.10.3[Full Changelog]

.Changed
- {url-issues}601[#601] Migrate from Bootstrap 4.x to 5.3
- Bumped dependencies
  kotlin, spring-boot-admin-starter-client, guava, feign, spring-cloud-starter-openfeign,
  gradle, reckon,
  jaxb, detekt,
  unit5, mockk, testcontainers, equalsverifier,
  github actions gradle-build-action, gradle-wrapper-validation, cache, upload-artifact and codeql


[[v1.10.2]]
== {url-tree}1.10.2[1.10.2] -- 2023-12-08

{url-cl}1.10.0++...++1.10.2[Full Changelog]

.Changed
- Bumped dependency
  kotlin,
  spring boot,
  wicket, wicketstuff, feign, spring-boot-admin-starter-client, jasperreports,
  testcontainers-java monorepo, equalsverifier,
  gradle, detektplugin, jaxb gradle plugin,
  setup-java action
- {url-issues}620[#620] Reverted (Data Migration: Update Abstract of old Studies with PM_ID)


[[v1.10.1]]
== {url-tree}1.10.1[1.10.1] -- 2023-12-07

{url-cl}1.10.0++...++1.10.2[Full Changelog]

.Changed
- {url-issues}620[#620] Data Migration: Update Abstract of old Studies with PM_ID


[[v1.10.0]]
== {url-tree}1.10.0[1.10.0] -- 2023-11-14

{url-cl}1.9.0++...++1.10.0[Full Changelog]

.Added
- {url-issues}604[#604] New (internal) Reference Abstract Report
.Changed
- {url-issues}338[#338] Migrate from Bootsrap 3.4 to 4.0
- Bumped dependency
  kotlin,
  spring-boot, spring-dependency-management, spring-boot-admin, feign, flyway, lombok,
  junit5, kotest, equalsverifier,
  detekt, reckon


[[v1.9.0]]
== {url-tree}1.9.0[1.9.0] -- 2023-10-08

{url-cl}1.8.11++...++1.9.0[Full Changelog]

.Changed
- Bumped dependency
  postgresql, kris,
  gradle,
  sonarqube,
  setup-java-action

.Removed
- Removed java platform 11 compatibility: Require minimum java platform 17.


[[v1.8.11]]
== {url-tree}1.8.11[1.8.11] -- 2023-09-03

{url-cl}1.8.10++...++1.8.11[Full Changelog]

.Changed
- Bumped kotlin, kotlinx-corouteines,
  wicket, wicketstuff,
  spring-boot, spring-dependency-management, spring-cloud-starter-openfeign, spring-boot-admin-starter-client,
  feign, flyway, kris-core, jasperreports
  lombok,
  junit5, kotest, mockk, equalsverifier, testcontainers
- Bumped gradle, sonarqube plugin, detekt
- Bumped checkout action, docker login action


[[v1.8.10]]
== {url-tree}1.8.10[1.8.10] -- 2023-06-25

{url-cl}1.8.9++...++1.8.10[Full Changelog]

.Changed
- Bumped spring-boot, kotlin, couroutines, wicket, wicketstuff, flyway, jasperreports,
  kotest, kluent, testcontainers, detekt, equalsverifier,
  sonarqube-gradle-plugin, docker-login-action
- Let scipamato run on JVM 17

.Fixed
- {url-issues}528[#528] Handle authors from PubMed with greek capital letters that otherwise fail author string validation



[[v1.8.9]]
== {url-tree}1.8.9[1.8.9] -- 2023-04-29

{url-cl}1.8.8++...++1.8.9[Full Changelog]

.Changed
- Bumped kotlin, jasperreports, flyway,
  junit-jupiter,
  gradle,
  reckon

.Fixed
- Typo in German localization when syncronizing core to public


[[v1.8.8]]
== {url-tree}1.8.8[1.8.8] -- 2023-04-20

{url-cl}1.8.7++...++1.8.8[Full Changelog]

.Changed
- Bumped spring-boot, wicket, wicketstuff, jasperreports, feign,
  kotest, mockk,
  gradle, gradle-jaxb-plugin


[[v1.8.7]]
== {url-tree}1.8.7[1.8.7] -- 2023-04-05

{url-cl}1.8.6++...++1.8.7[Full Changelog]

.Changed
- {url-issues}463[#463] Synchronization from core to public to use german labels for concatenated short studies
- Bumped kotlin, flyway, KRis, gradle, testcontainers


[[v1.8.6]]
== {url-tree}1.8.6[1.8.6] -- 2023-03-25

{url-cl}1.8.5++...++1.8.6[Full Changelog]

.Changed
- Bumped spring-boot, flyway, KRis, kotlin-logging, feign, spring-cloud-start-openfeign,
  jasperreports, wicket-jquery-ui,
  gradle-wrapper, lombok, sonarqube-gradle-plugin,
  kotest, mockk, equalsverifier


[[v1.8.5]]
== {url-tree}1.8.5[1.8.5] -- 2023-01-19

{url-cl}1.8.4++...++1.8.5[Full Changelog]

.Added
- kotest

.Changed
- Bumped kotlin, spring-boot, wicket, wicketstuff, wicket-spring-boot-starter, spring-boot-admin-starter-client, flyway, lombok, kris
  spring-dependency-management, spring-cloud-starter-openfeign, feign, kotlin-loggin,
  mockk, spring-mockk, kluent, equalsverifier, junit5, kotest, testcontainers,
  gradle, sonarqube-plugin, detekt,
  login-action
- {url-issues}360[#360] Use version catalogs (instead of buildSrc/Lib) for version management

.Removed
- spek, kwik, jcenter


[[v1.8.4]]
== {url-tree}1.8.4[1.8.4] -- 2022-09-24

{url-cl}1.8.3++...++1.8.4[Full Changelog]

.Changed
- Bumped spring-boot, wicket-jquery-ui, spring-boot-admin, flyway, openfeign, spring-dependency-management,
  junit-jupiter, spek, mockk,
  jaxb-gradle-plugin, lombok-gradle-plugin


[[v1.8.3]]
== {url-tree}1.8.3[1.8.3] -- 2022-08-18

{url-cl}1.8.2++...++1.8.3[Full Changelog]

.Changed
- Bumped spring-boot, spring dependency-management, spring-boot-admin,
  junit-jupiter, mockk, equalsverifier


[[v1.8.2]]
== {url-tree}1.8.2[1.8.2] -- 2022-07-22

{url-cl}1.8.1++...++1.8.2[Full Changelog]

.Changed
- Bumped spring-boot, kotlin, coroutines, wicket, wicketstuff, jOOQ, openfeign, spring-dependency-management, jasperreports,
  detekt, testcontainers,
  gradle-wrapper, lombok-gradle-plugin


[[v1.8.1]]
== {url-tree}1.8.1[1.8.1] -- 2022-06-27

{url-cl}1.8.0++...++1.8.1[Full Changelog]

.Fixed
- Main class name for core application after conversion to kotlin



[[v1.8.0]]
== {url-tree}1.8.0[1.8.0] -- 2022-06-27

{url-cl}1.7.12++...++1.8.0[Full Changelog]

.Changed
- Bumped spring-boot

.Fixed
- {url-issues}344[#344] Handle spring batch data synchronization from core to public asynchronously


[[v1.7.12]]
== {url-tree}1.7.12[1.7.12] -- 2022-06-25

{url-cl}1.7.11++...++1.7.12[Full Changelog]

.Changed
- Bumped spring-boot, wicket-jquery-ui, flyway, kotlin, kotlinx-coroutines, jOOQ,
  spring-cloud-starter,
  spring-boot-admin-starter-client,
  lombok-gradle-plugin, sonarqube-gradle-plugin


[[v1.7.11]]
== {url-tree}1.7.11[1.7.11] -- 2022-05-21

{url-cl}1.7.10++...++1.7.11[Full Changelog]

.Changed
- Bumped spring-boot, wicket and wicketstuff, flyway, kotlin-logging,
  spring-cloud, spring-boot-admin,
  mockk, testcontainers,
  lombok-gradle-plugin
- {url-issues}333[#333] Organize licenses for license report


[[v1.7.10]]
== {url-tree}1.7.10[1.7.10] -- 2022-04-21

{url-cl}1.7.9++...++1.7.10[Full Changelog]

.Changed
- Bumped spring-boot, kotlin, wicket, wicketstuff, jOOQ, flyway, detekt, spring-boot-admin, coroutines, testcontainers,
  lombok-gradle-plugin

[[v1.7.9]]
== {url-tree}1.7.9[1.7.9] -- 2022-04-03

{url-cl}1.7.8++...++1.7.9[Full Changelog]


.Changed
- Bumped kotlin, spring-boot, wicket and wicketstuff, jasperreports, flyway, spring-boot-admin,
  gradle-wrapper



[[v1.7.8]]
== {url-tree}1.7.8[1.7.8] -- 2022-03-25

{url-cl}1.7.7++...++1.7.8[Full Changelog]

.Changed
- Bumped spring-boot, flyway, jOOQ, spring-cloud-starter, gradle-wrapper, spek, mockk, equalsverifier


[[v1.7.7]]
== {url-tree}1.7.7[1.7.7] -- 2022-02-25

{url-cl}1.7.6++...++1.7.7[Full Changelog]

.Changed
- Bumped spring-boot, wicket, wicketstuff, wicket-jquery-ui, spring-boot-admin-starter, jOOQ, flyway, jasperreports, gradle,
  springmockk, equals-verifier,
  gradle versions plugin, lombok-gradle-plugin, reckon-gradle-plugin


[[v1.7.6]]
== {url-tree}1.7.6[1.7.6] -- 2022-01-21

{url-cl}1.7.5++...++1.7.6[Full Changelog]

.Changed
- Bump spring-boot, gradle-wrapper, jOOQ, flyway, wicket-jquery-ui, KRis-core, mockk, openfeign, versions gradle plugin,
  equalsverifier, spring-boot-admin, testcontainers


[[v1.7.5]]
== {url-tree}1.7.5[1.7.5] -- 2021-12-22

{url-cl}1.7.4++...++1.7.5[Full Changelog]

.Changed
- Bump spring-boot, wicket-spring-boot-starter, flyway


[[v1.7.4]]
== {url-tree}1.7.4[1.7.4] -- 2021-12-20

{url-cl}1.7.3++...++1.7.4[Full Changelog]

.Security
- [CVE-2021-42550] Bump logback from 1.2.7 to 1.2.9


[[v1.7.3]]
== {url-tree}1.7.3[1.7.3] -- 2021-12-19

{url-cl}1.7.2++...++1.7.3[Full Changelog]

.Added
- Bumped wicket-spring-boot-starter, springmockk, spring-boot-admin, kotlin-loggin

.Security
- [CVE-2021-45105] Bump log4j from 2.16.0 to 2.17.0


[[v1.7.2]]
== {url-tree}1.7.2[1.7.2] -- 2021-12-15

{url-cl}1.7.1++...++1.7.2[Full Changelog]

.Changed
- Bumped flyway, equalsverifier, gradle

.Security
- [CVE-2021-44228] (Log4Shell): Bump log4j from 2.15.0 to 2.16.0


[[v1.7.1]]
== {url-tree}1.7.1[1.7.1] -- 2021-12-14

{url-cl}1.7.0++...++1.7.1[Full Changelog]


.Changed
- Bumped kotlin, kotlin-loggin, flyway, wicketstuff

.Security
- [CVE 2021-44228] (Log4Shell): Even though SciPaMaTo uses logback for logging, we now use log4j-2.15.0 for the api and log4j-to-slf4j to be on the safe side.


[[v1.7.0]]
== {url-tree}1.7.0[1.7.0] -- 2021-12-07

{url-cl}1.6.9++...++1.7.0[Full Changelog]

.Changed
- Bumped spring-boot, spring-cloud, spring-cloud-starter, jOOQ, flyway, wicket,
  gradle, detekt, junit-jupiter, kotlin-logging, equalsverifier, reckon

.Removed
- dependency on jackson-module-kotlin, a few explicit jaxb-dependencies


[[v1.6.9]]
== {url-tree}1.6.9[1.6.9] -- 2021-11-18

{url-cl}1.6.8++...++1.6.9[Full Changelog]

.Added
- {url-issues}306[#306] Population Filter & Search

.Changed
- Bumped spring-boot, kotlin, flyway, mockk


[[v1.6.8]]
== {url-tree}1.6.8[1.6.8] -- 2021-11-14

{url-cl}1.6.7++...++1.6.8[Full Changelog]

.Added
- {url-issues}292[#292] Add option to exclude codes from a complex search

.Changed
- Bumped gradle, spring-boot-admin, wicket, wicketstuff, flyway, jasperreports,
  lombok-gradle-plugin, jackson-module-kotlin


[[v1.6.7]]
== {url-tree}1.6.7[1.6.7] -- 2021-10-26

{url-cl}1.6.6++...++1.6.7[Full Changelog]

.Changed
- Bumped spring-boot, jackons-module-kotlin, wicket-jquery-ui, spring-boot-starter-admin,
  flyway, openfeign, jasperrports,
  testcontainers, equalsverifier

.Fixed
- {url-issues}300[#300] Fix synchronization corner case with Newsletters with Papers without code


[[v1.6.6]]
== {url-tree}1.6.6[1.6.6] -- 2021-09-23

{url-cl}1.6.5++...++1.6.6[Full Changelog]

.Changed
- Bumped spring-boot


[[v1.6.5]]
== {url-tree}1.6.5[1.6.5] -- 2021-09-23

{url-cl}1.6.4++...++1.6.5[Full Changelog]

.Changed
- Bumped kotlin, spring-boot-admin, kotlin-logging, detekt, wicket, wicketstuff, flyway, jOOQ,
  junit-jupiter,
  lombok-gradle-plugin

.Fixed
- {url-issues}294[#294] Searching by Newsletter Issue and other fields don't provide all search options


[[v1.6.4]]
== {url-tree}1.6.4[1.6.4] -- 2021-08-22

{url-cl}1.6.3++...++1.6.4[Full Changelog]

.Changed
- Bumped kotlin, spring-boot, gradle, flyway, kluent, kotlin-logging, jaxb-core and impl
  spring-boot-admin, openfeign, detekt, equalsverifier, spek, testcontainers, lombok-gradle-plugin


[[v1.6.3]]
== {url-tree}1.6.3[1.6.3] -- 2021-07-10

{url-cl}1.6.2++...++1.6.3[Full Changelog]

.Changed
- Bumped wicket, wicketstuff, jackson-kotlin, flyway, equalsverifier

.Fixed
- Fixed typo in Code 1S in German


[[v1.6.2]]
== {url-tree}1.6.2[1.6.2] -- 2021-07-04

{url-cl}1.6.1++...++1.6.2[Full Changelog]

.Changed
- Bump spring-boot, kotlin, kluent, mockk, spring-boot-admin, jOOQ, gradle,
  wicket-jquery-ui, flyway


[[v1.6.1]]
== {url-tree}1.6.1[1.6.1] -- 2021-06-19

{url-cl}1.6.0++...++1.6.1[Full Changelog]

.Changed
- Bumped spring-boot, flyway, gradle-versions-plugin, jaxb-gradle-plugin, kotlin-logging
  spring-cloud, spring-cloud-starter, gradle-wrapper, kluent, sonarqube-gradle-plugin


[[v1.6.0]]
== {url-tree}1.6.0[1.6.0] -- 2021-05-26

{url-cl}1.5.12++...++1.6.0[Full Changelog]

.Changed
- Bump spring-boot, gradle-wrapper, kotlin, gradle-testsets-plugin, license-gradle-plugin, jaxbCore, openfeign
  jOOQ, flyway, jasperreports, junit, detekt, equalsverifier


[[v1.5.12]]
== {url-tree}1.5.12[1.5.12] -- 2021-05-01

{url-cl}1.5.11++...++1.5.12[Full Changelog]

.Changed
- Bump flyway, jaxb-impl, SonarQube gradle plugin
- Converted core-sync to kotlin

.Fixed
- Regression from #270 with puplicationYear being populated multiple times


[[v1.5.11]]
== {url-tree}1.5.11[1.5.11] -- 2021-04-26

{url-cl}1.5.10++...++1.5.11[Full Changelog]

.Fixed
- Fixed regression in 1.5.10 with optimized layout


[[v1.5.10]]
== {url-tree}1.5.10[1.5.10] -- 2021-04-25

{url-cl}1.5.9++...++1.5.10[Full Changelog]

.Changed
- Bumped spring-boot, wicket, wicketstuff, wicket-jqury-ui, wicket-bootstrap, flyway, jaxb-gradle-plugin
  lombok-gradle-plugin, jackson-kotlin, spring-boot-admin-starter, testcontainers, equalsverifier, jOOQ

.Fixed
- Optimized Layout for very small screens


[[v1.5.9]]
== {url-tree}1.5.9[1.5.9] -- 2021-03-30

{url-cl}1.5.8++...++1.5.9[Full Changelog]

.Added
- {url-issues}265[#265] Enable complex search to filter for papers with or without attachments or by attachment name

.Changed
- Bumped spring-boot, kotlin, flyway, detekt, jackson-kotlin, gradle versions-plugin, kotlin-logging, mockk,
  spring-cloud-starter, openfeign, KRis


[[v1.5.8]]
== {url-tree}1.5.8[1.5.8] -- 2021-03-03

{url-cl}1.5.7++...++1.5.8[Full Changelog]

.Changed
- Bumped spring-boot, kotlin, jOOQ, flyway, equalsverifier, kris, junit, mockk, gradle-wrapper
  wicket-jquery-ui, spring-boot-admin, testcontainers, font-awesome

.Fixed
- {url-issues}262[#262] Restore ability to delete searches (Restore Confirmation behavior)


[[v1.5.7]]
== {url-tree}1.5.7[1.5.7] -- 2021-01-27

{url-cl}1.5.6++...++1.5.7[Full Changelog]


.Added
- {url-issues}253[#253] Review CSV Export - Followup


[[v1.5.6]]
== {url-tree}1.5.6[1.5.6] -- 2021-01-27

{url-cl}1.5.5++...++1.5.6[Full Changelog]

.Added
- {url-issues}250[#250] Review CSV Export

.Changed
- Bumped spring-boot, spring-cloud-starter, spring-cloud-openfeign, jOOQ
  spek, testcontainers, kotlin-logging, detekt, flyway, wicket-jquery-ui,
  mockk, kluent, springmockk, gradle-wrapper, jackson-kotlin,
  spring-dependency-management, equalsverifier, sonarqube-plugin


[[v1.5.5]]
== {url-tree}1.5.5[1.5.5] -- 2020-12-10

{url-cl}1.5.4++...++1.5.5[Full Changelog]

.Changed
- Bumped kotlin, spring-cloud, spring-cloud-starter, flyway

.Fixed
- {url-issues}247[#247] Fix captions in Paper Summary PDF


[[v1.5.4]]
== {url-tree}1.5.4[1.5.4] -- 2020-12-01

{url-cl}1.5.3++...++1.5.4[Full Changelog]

.Changed
- Bumped spring-boot, kotlin, spring-cloud, spring-cloud-starter, jooq, flyway,
  wicket, wicketstuff, wicket-bootstrap, kwik, jaxb, jackson-kotlin,
  gradle, spek, kluent, spring-mockk, spring-boot-admin, jaxb-gradle-plugin, mockk

.Fixed
- {url-issues}242[#242] Only allow uploading attachments once paper is saved
- {url-issues}244[#244] Fix searching papers by pmId


[[v1.5.3]]
== {url-tree}1.5.3[1.5.3] -- 2020-11-08

{url-cl}1.5.2++...++1.5.3[Full Changelog]

.Added
- {url-issues}236[#236] Prepopulate field 'result exposure range' with value 'µg/m3' for new papers

.Changed
- Follow up of {url-issues}215[#215]: Enlarge PMID field, make DOI smaller on smaller screens
- {url-issues}238[#238] SciPaMaTo-Public: Hide 'Back' button from paper detail page when opend from result panel


[[v1.5.2]]
== {url-tree}1.5.2[1.5.2] -- 2020-11-07

{url-cl}1.5.1++...++1.5.2[Full Changelog]

.Changed
- Bumped jasperreports, KRis, jOOQ, javax.el, testcontainers

.Fixed
- {url-issues}232[#232] Fix regression: Persisting papers with codes broken


[[v1.5.1]]
== {url-tree}1.5.1[1.5.1] -- 2020-10-31

{url-cl}1.5.0++...++1.5.1[Full Changelog]

.Changed
- Bumped spring-boot, wicket, wicket-bootstrap, wicket-jquery-ui, jOOQ, detekt, mockk, kluent,
  kwik, kris, jasperreports, font-awesome, flyway, gradle, equalsverifier, lombok-gradle-plugin
- Kotlin Conversion of common-pesistence-api, common-persistence-jooq, common-wicket, public-*

.Fixed
- {url-issues}114[#114] Reactivate integration-tests for SciPaMaTo public-web


[[v1.5.0]]
== {url-tree}1.5.0[1.5.0] -- 2020-10-20

{url-cl}1.4.9++...++1.5.0[Full Changelog]

.Changed
- Bumped gradle, kotlin, kwik, equalsverifier, detekt, spek, junit,
  spring-cloud-starter, spring-cloud-openfeign, kotlin-logging,
  lombok-plugin, reckon gradle plugin
- Renamed tab label in PaperEntryPage to align with field order
- {url-issues}198[#198] Migrate to Wicket 9.0
- {url-issues}215[#215] Improve Layout of various pages for small/medium screens


[[v1.4.10]]
== {url-tree}1.4.10[1.4.10] -- 2020-08-14

{url-cl}1.4.9++...++1.4.10[Full Changelog]

.Changed
- Bumped spring-boot, gradle-wrapper, kwik, springmockk, detekt, spring-boot-admin
  spring-dependency-management plugin, lombok gradle plugin
- Moved ID column in Result panel table to the end
- Added some more logs for repo methods changing data


[[v1.4.9]]
== {url-tree}1.4.9[1.4.9] -- 2020-08-05

{url-cl}1.4.8++...++1.4.9[Full Changelog]

.Changed
- {url-issues}202[#202] Auto-correct ahead-of-print articles from PubMed - case-insensitivity

.Fixed
- Wiki: fixed some typos


[[v1.4.8]]
== {url-tree}1.4.8[1.4.8] -- 2020-08-03

{url-cl}1.4.7++...++1.4.8[Full Changelog]

.Changed
- Bumped spring-boot-starter, jOOQ, spring-boot-admin, spring-cloud, spring-cloud-starter-openfeign
  jasperreports

.Fixed
- {url-issues}204[#204] Fix storing newsletter topic sort


[[v1.4.7]]
== {url-tree}1.4.7[1.4.7] -- 2020-07-21

{url-cl}1.4.6++...++1.4.7[Full Changelog]

.Added
- {url-issues}202[#202] Auto-correct ahead-of-print articles from PubMed

.Changed
- Bumped detekt, jooq-modelator, gradle-wrapper, jasperreports, spring-cloud, jooq,
  wicket, wicket-spring-boot-starter, wicketstuff, wicket-jquery-ui, wicket-bootstrap
  kotlin-logging, openfeign, fontawesome, equalsverifier, spek, spring-mockk,
  jooq-modelator-plugin, kwik
- {url-issues}196[#196] Properly use UTF-8 property files for wicket localization
- Rename master branch to main

.Removed
- {url-issues}177[#177] Removed mockito, mockito-kotlin, assertj. Converted all tests to kotlin.


[[v1.4.6]]
== {url-tree}1.4.6[1.4.6] -- 2020-06-22

{url-cl}1.4.5++...++1.4.6[Full Changelog]

.Changed
- Bumped spring-boot-starter, spring-boot-admin, spring-cloud-starter, jOOQ, KRis, kotlin-logging, jaxb-impl,
  detekt, gradle-wrapper, spek, gadle, wicket-jquery-ui, equalsverifier, testcontainers, lombok-gradle-plugin,
  sonarqube-gradle-plugin, jooqModelator


[[v1.4.5]]
== {url-tree}1.4.5[1.4.5] -- 2020-05-11

{url-cl}1.4.4++...++1.4.5[Full Changelog]

.Changed
- Bumped spring-boot, kotlin, detekt, KRis, kwik, wicket-boostrap, wicketstuff, font-awesome,
  gradle, junit-jupter, kluent, mockk, spring-cloud, wicket, KRis, testcontainers, openfeign
  lombok-gradle-plugin
- {url-issues}179[#179] Enrich Changelog with Full Changelog and link to tree

.Removed
- apache-io, commons-lang3, commons-collections4, jool


[[v1.4.4]]
== {url-tree}1.4.4[1.4.4] -- 2020-03-27

{url-cl}1.4.3++...++1.4.4[Full Changelog]

.Changed
- Bumped spring-boot, kotlin, gradle, detekt, jasperreports, junit, spring-cloud and starter,
  kotlin-logging, openfeign, equalsverifier, testcontainers, mockito, lombok-plugin, jaxb-plugin


[[v1.4.3]]
== {url-tree}1.4.3[1.4.3] -- 2020-03-13

{url-cl}1.4.2++...++1.4.3[Full Changelog]

.Added
- Bumped kotlin, gradle-wrapper, jasperreports, spek, kluent, kris


[[v1.4.2]]
== {url-tree}1.4.2[1.4.2] -- 2020-03-02

{url-cl}1.4.1++...++1.4.2[Full Changelog]

.Changed
- Bumped spring-boot-starter, jOOQ, wicket-spring-boot-starter, junit, gradle-wrapper, spring-boot-admin, kwik, detekt,
  equlalsverifier, testcontainers, mockito, spring-dependency-management plugin, lombok plugin, jaxb-plugin
- {url-issues}129[#129] Replace copied JRis classes with ch.difty.kris:kris-core


[[v1.4.1]]
== {url-tree}1.4.1[1.4.1] -- 2020-01-18

{url-cl}1.4.0++...++1.4.1[Full Changelog]


.Changed
- Bump dependencies: spring-boot-starter-parent, gradle-wrapper, wicket-bootstrap


[[v1.4.0]]
== {url-tree}1.4.0[1.4.0] -- 2020-01-14

{url-cl}scipamato-1.3.1++...++1.4.0[Full Changelog]

.Changed
- {url-issues}136[#136] Upgrade Spring-Boot to 2.2, Flyway 6.0, jOOQ 3.12.1
- Bump dependencies: spring-boot-starter-parent, wicket, sicketstuff, wicket-spring-boot, kotlin, jOOQ, detekt, testSet-plugin, mockk, lombok-plugin
  wicket-jquery-ui, spring-cloud-starter, openfeign, testcontainers, mockito, kwik, kluent, spring-dependency-management, reckon, jaxb plugin,
  jasperreports, spring-boot-admin-starter-client, equalsverifier, spek
- {url-issues}150[#150] Move gradle project from /implementation/scipamato into git root


[[v1.3.1]]
== {url-tree}1.3.1[1.3.1] -- 2019-10-15

{url-cl}scipamato-1.3.0++...++scipamato-1.3.1[Full Changelog]

.Changed
- {url-issues}119[#119] Core - Truncate Display value for SearchOrder to not have the combobox in the
  search order panel grow excessively.
- {url-issues}138[#138] Added Nullability annotations in code
- Dependency updates for spring-boot-starter, spring-cloud, spring-cloud-starter, openfeign, jasperreports,
  font-awesome, equalsverifier, testcontainers, mockito
- Plugin updates for gradle-lombok-plugin, sonarqube
- Various technical improvements ({url-issues}124[#124] - thanks to @jcornaz, {url-issues}138[#138], {url-issues}133[#133])


[[v1.3.0]]
== {url-tree}scipamato-1.3.0[1.3.0] -- 2019-09-25

{url-cl}scipamato-1.2.4++...++scipamato-1.3.0[Full Changelog]

.Added
- {url-issues}118[#118] Core - Export stuies in RIS format for import into citiation programs

.Changed
- Dependency updates for spring-boot-starter, wicket, wicketstuff, wicket-bootstrap, openfeign,
  junit, testcontainers, lombok-plugin, jooqmodelator-plugin

.Fixed
- {url-issues}127[#127] Core - Remove LoadingBehavior where not absolutely necessary


[[v1.2.4]]
== {url-tree}scipamato-1.2.4[1.2.4] -- 2019-08-20

{url-cl}scipamato-1.2.3++...++scipamato-1.2.4[Full Changelog]

.Changed
- Dependency updates for spring-boot-starter, openfeign, font-awesome, mockito,
  lombok-plugin, flyway-plugin, gradle-wrapper, jooq

.Fixed
- {url-issues}109[#109] Core - Restore searching in methods fields (with positive and negative
  search terms)


[[v1.2.3]]
== {url-tree}scipamato-1.2.3[1.2.3] -- 2019-07-20

{url-cl}scipamato-1.2.2++...++scipamato-1.2.3[Full Changelog]

.Changed
- Dependency updates for kotlin, junit, lombok-plugin, commons-collections4, font-awesome,
  gradle-wrapper, mockito, spring-boot-admin

.Fixed
- {url-issues}105[#105] Core - Restore ability to create new searches with more than 20 saved searches


[[v1.2.2]]
== {url-tree}scipamato-1.2.2[1.2.2] -- 2019-06-26

{url-cl}scipamato-1.2.1++...++scipamato-1.2.2[Full Changelog]

.Changed
- Bumped version of spring-boot-starter, spring-cloud, openfeign, spring-dependency-management, jasperreports, lombok-plugin


[[v1.2.1]]
== {url-tree}scipamato-1.2.1[1.2.1] -- 2019-06-18

{url-cl}scipamato-1.2.0++...++scipamato-1.2.1[Full Changelog]

.Added
- {url-issues}91[#91] Core - complex search enhancement: Method search to include short study fields

.Changed
- Bumped versions of spring-dependency-management, wicket-spring-boot-starter,
  wicket, wicketstuff, wicket-bootstrap, jasperreports, font-awesome, flyway-plugin,
  jaxb-plugin


[[v1.2.0]]
== {url-tree}scipamato-1.2.0[1.2.0] -- 2019-05-24

{url-cl}scipamato-1.1.6++...++scipamato-1.2.0[Full Changelog]

.Changed
- Bumped versions of spring-boot-starter, wicket, wicket-bootstrap, wicket-webjars, jasperreports and -fonts,
  equalsverifier, spring-boot-admin-starter-client, bootstrap, font-awesome, flyway, lombok-plugin
- {url-issues}80[#80] - Migrate from JUnit4 and JUnitParams to JUnit5
- {url-issues}82[#82] - Migrating the build system from using maven to gradle

.Fixed
- {url-issues}69[#69] - Fix Sonar warning: Use project relative paths instead of module relative paths
- {url-issues}82[#82] - Fix searching for publication year ranges and for ID


[[v1.1.6]]
== {url-tree}scipamato-1.1.6[1.1.6] -- 2019-03-27

{url-cl}scipamato-1.1.5++...++scipamato-1.1.6[Full Changelog]

.Fixed
- {url-issues}70[#70] - Core: Filter Newsletters by newsletter topic - fix query


[[v1.1.5]]
== {url-tree}scipamato-1.1.5[1.1.5] -- 2019-03-22

{url-cl}scipamato-1.1.4++...++scipamato-1.1.5[Full Changelog]

.Changed
- Bumped version of asm, spring-cloud, jasperreports, commons-collections4,
  spring-boot-admin-starter-client, equalsverifier, wicket-jquery-ui

.Fixed
- {url-issues}2[#2] - Core: Using Back button from PaperEntryPage breaks PDF Report generation
- {url-issues}73[#73] - Public: Allow starting SciPaMaTo-Public in development profile
- {url-issues}12[#12] - Core-Sync: Improve Hikari configuration


[[v1.1.4]]
== {url-tree}scipamato-1.1.4[1.1.4] -- 2019-03-13

{url-cl}scipamato-1.1.3++...++scipamato-1.1.4[Full Changelog]

.Added
- {url-issues}70[#70] - Core: Filter Newsletters by newsletter topic
- Added many wiki pages
- Test coverage, refactorings and small optimizations behind the scene

.Changed
- {url-issues}63[#63] - Core: Change layout of new study fields panel in paper edit page - take 2
- Bumped spring-boot-parent to 2.1.3

.Fixed
- {url-issues}50[#50] - Public: pym integration into CMS - Fix resizing of the page height after
  switching to a different new study issue with a shorter or longer list than the most recent one
  (The issue was fixed in the pym integration in the parent CMS page of SwissTPH by CS2). SciPaMaTo
  only assisted with issueing log statements on the browser console.


[[v1.1.3]]
== {url-tree}scipamato-1.1.3[1.1.3] -- 2019-02-12

{url-cl}scipamato-1.1.2++...++scipamato-1.1.3[Full Changelog]

.Added
- {url-issues}56[#56] - Public: Add help link in Public Filter page pointing to wiki in Github

.Changed
- Bumped wicket to 8.3.0, jacoco-maven-plugin to 0.8.3, wicket-bootstrap to 2.0.7
- Change java source/target version to java 11
- {url-issues}63[#63] - Core: Change layout of new study fields panel in paper edit page


[[v1.1.2]]
== {url-tree}scipamato-1.1.2[1.1.2] -- 2019-01-29

{url-cl}scipamato-1.1.1++...++scipamato-1.1.2[Full Changelog]

.Changed
- Updated the wiki to better reflect the current state of the project

.Fixed
- {url-issues}44[#44] - Core & Public: Fix typo in Code '4H' (en): cardovascular -> cardiovascular
- {url-issues}46[#46] - Sync: Fix exception (NPE) when synchronizing NewStudyTopics from Core to Public
- {url-issues}48[#48] - Core: Provide better feedback about the underlying cause if the PubMed API is unable to retrieve an article
- {url-issues}51[#51] - Core: Newsletter Edit Page: Issue and Issue Date only enabled for newsletters in status `In Progress`
- {url-issues}52[#52] - Public: Fix direct access to paper detail page via page parameters


[[v1.1.1]]
== {url-tree}scipamato-1.1.1[1.1.1] -- 2019-01-16

{url-cl}scipamato-1.1.0++...++scipamato-1.1.1[Full Changelog]

.Changed
- {url-issues}34[#34] - Dependency updates: spring-boot-parent-2.1.2, jaxb-impl, spring-boot-admin-starter-client,equalsverifier, sonar-maven-plugin

.Removed
- {url-issues}42[#42] - Core: Remove ShortList report and rename ShortList+ to Results

.Fixed
- {url-issues}36[#36] - Core: Fix spacing in paper summary table PDF to prevent result field to be cut off
- {url-issues}38[#38] - Core: Fix `Class does not have a visible default constructor` in PaperEntryPage
- {url-issues}39[#39] - Core: Fix deleting search orders in the SearchOrderPage


[[v1.1.0]]
== {url-tree}scipamato-1.1.0[1.1.0] -- 2018-12-20

{url-cl}scipamato-1.0.5++...++scipamato-1.1.0[Full Changelog]

.Changed
- {url-issues}13[#13] - Core: SummaryPDF to show concatenated short fields if main fields methods/population/results are null.
  Also search by population place in quick search field `method`.
- {url-issues}17[#17] - Core: Let user filter by newsletter. Also enable (and fix) searching by newsletter topic and headline.
  Also fix auto-saving behavior of the non-tabbed fields in the Search Page.
- {url-issues}14[#14] - Migrate from local SonarQube server to SonarCloud

.Fixed
- {url-issues}16[#16] - Core: Fix editing Search Conditions by not automatically closing the page and triggering the search
  after having updated a field.
- Fixed License in POM file to reflecte the change from GPL3 to BSD-3


[[v1.0.5]]
== {url-tree}scipamato-1.0.5[1.0.5] -- 2018-12-03

{url-cl}scipamato-1.0.4++...++scipamato-1.0.5[Full Changelog]

.Changed
- {url-issues}9[#9] - Public: Reorder the filter fields in the SimpleFilterPanel
- Core: PaperEntryPage: Reduce row count of title field to 3

.Removed
- {url-issues}7[#7] - Core: Remove Validation from PaperEditPage. Message in the Synchronization Page seems to be enough.

.Fixed
- {url-issues}6[#6] - Core: Extension of the Literature Review PDF Report: Don't allow pagebreak within study


[[v1.0.4]]
== {url-tree}scipamato-1.0.4[1.0.4] -- 2018-12-02

{url-cl}scipamato-1.0.3++...++scipamato-1.0.4[Full Changelog]

.Added
- {url-issues}6[#6] - Core: Extension of the Literature Review PDF Report: Original without the goals field, additional one called Literature Review Plus with the goals field
- {url-issues}9[#9] - Public: Offer to search by study title

.Changed
- {url-issues}5[#5] - Core: Tweak Layout of paper entry page for smaller resolution screens
- {url-issues}7[#7] - Sync: Improve Synchronization feedback:
** Let the entire job fail if one job step fails
** Provide warn messages for unsynchronized entities (papers with no codes assigned)
- Updated dependencies: spring-boot, spring-boot-admin-starter-client, equalsverifier


[[v1.0.3]]
== {url-tree}scipamato-1.0.3[1.0.3] -- 2018-11-26

{url-cl}scipamato-1.0.2++...++scipamato-1.0.3[Full Changelog]

.Added
- Enhanced test coverage

.Fixed
- {url-issues}3[#3]: Core: Fix Exception when importing new paper from PubMed
- a couple of minor bugs


[[v1.0.2]]
== {url-tree}scipamato-1.0.2[1.0.2] -- 2018-11-26

{url-cl}scipamato-1.0.1++...++scipamato-1.0.2[Full Changelog]

.Added
- {url-issues}3[#3]: Core: Excluding papers from search from within paper edit page should not jump to the result page

.Fixed
- {url-issues}4[#4]: Core: Navigating from one paper to the next/previous in the paper entry page should keep the focus on the previously selected tab panel.


[[v1.0.1]]
== {url-tree}scipamato-1.0.1[1.0.1] -- 2018-11-21

{url-cl}scipamato-1.0.0++...++scipamato-1.0.1[Full Changelog]

.Added
- {url-issues}1[#1]: Translate Exception into more user friendly form:
                     DataViolationException when trying to delete code

.Changed
- Bumped version of dependencies: wicket 8.2.0, wicket-spring-boot-starter 2.1.5, wicket-bootstrap 2.0.6

.Fixed
- {url-issues}2[#2]: Error when creating literature review PDF after using the browsers back button (10/15)


[[v1.0.0]]
== {url-tree}scipamato-1.0.0[1.0.0] -- 2018-11-11

{url-cl}scipamato-0.9.4++...++scipamato-1.1.0[Full Changelog]

.Added
- 09/87: New short field ('Kurzerfassungs-Feld') conclusion.
         Synched to Public result field. Shown in some reports.
- 09/05 - Core: Add facilities to manage codes and code classes

.Changed
- Core: Moved Sync Menu into Reference Data Menu
- Public: Layout tweak in NewStudy list page
- Bumped dependencies: spring-boot-2.1.0, bval-jsr, spring-boot-admin-starter-client, equalsverifier
- Simplified dependency management:
** Remove explicit version overrides for dependencies managed already in spring-boot-super-pom (jOOQ,
   Flyway, lombok, mockito, assertj, byte-buddy, commons-lang3, jaxb-api, jaxb-runtime, maven-plugins
** Remove dependency management entry or at least version number for dependencies managed already
    in spring-boot-super-pom
- Migration to spring-boot-starter-parent-2.1.0
** Remove obsolete spring bean overrides
** Enable spring.main.allow-bean-definition-overriding where requiered (a. in case of overriding
    beans with test beans (test profile) and b. with spring batch jobRepository (production)
- Refactored ListPages for Codes, Keywords, Newsletter Topics abstracting common code
- 09/93 - Public: Limit width of keyword filter field

.Fixed
- 09/84 - Sync: Fix issue with obsolete reference data records in SciPaMaTo-Public not being deleted during sync.
  Also fixed foreign key constraint violation when trying to sync topics of newsletters that are not published.
  Fix sync of newsletter related tables based on wrong foreign key constraints
- 09/86 - Public: Fix padding in public search page
- 09/88 - Public: Fix typos


[[v0.9.4]]
== {url-tree}scipamato-0.9.4[0.9.4] -- 2018-10-28

{url-cl}scipamato-0.9.3++...++scipamato-0.9.4[Full Changelog]

.Added
- 09/73 - Core: Add facility to manage the keywords

.Changed
- Bumped dependencies spring-cloud, flyway
- Slightly improve the newsletter topic maintenance infrastructure (layout, back-button)

.Fixed
- 09/82 - Core: Fix Literaturliste-PDF-Report (include Goals and DOI)


[[v0.9.3]]
== {url-tree}scipamato-0.9.3[0.9.3] -- 2018-10-24

{url-cl}scipamato-0.9.2++...++scipamato-0.9.3[Full Changelog]

.Added

- 09/10 - Public: Allow filtering by keywords
- 09/80 - Core: Disable newsletter fields if paper is not assigned to newsletter

.Changed
- Update dependencies spring-boot-parent, flyway, byte-buddy, commons-lang3, mockito, equalsverifier,
  wicket-jquery-ui, byte-buddy, jaxb-api, jaxb-impl, jaxb-runtime, spring-boot-starter-admin-client

.Fixed
- 09/67 - Core: Remove obsolete newsletter topics from sort list
- 09/74 - Core: Prevent double clicks on buttons and disable save button until auto-save completed
- 09/44 - Core: Fix core access for users of type VIEWER


[[v0.9.2]]
== {url-tree}scipamato-0.9.2[0.9.2] -- 2018-10-03

{url-cl}scipamato-0.9.1++...++scipamato-0.9.2[Full Changelog]

.Changed
- Updated dependencies wicket, wicketstuff, wicket-bootstrap
- 09/64 - Core: Prepend the first word of the brand to the number label in the edit page
- 09/63 - Core: Make newPaper button in PaperListPage more distinguishable (Type Primary)
- 09/57 - Core: Do alert if Original Abstract differs between Pubmed and SciPaMaTo. Normalize line ends before comparing
- 09/72 - Core: Add newly created paper to head of id list for moving back and forth (after first save)

.Fixed
- Maximum Upload File Size correctly reset to 10M
- 09/57 - Core: Fix Pubmed import from file for certain html tags in text
                Not fixed for direct import from pubmed! (new dtd can't be parsed by jaxb)
- 09/59 - Core -> Public: Make sync more resilient by basing the sync on number instead of id


[[v0.9.1]]
== {url-tree}scipamato-0.9.1[0.9.1] -- 2018-09-17

{url-cl}scipamato-0.9.0++...++scipamato-0.9.1[Full Changelog]

.Added
- Public: French translation of the PublicPaperDetailPage
- 09/56 - Core: Access Pubmed using api_key if configured

.Changed
- Bumped dependency versions: spring-boot-starter, jOOQ, mockito, byte-buddy, equalsverifier, sonar-maven-plugin

.Fixed
- 09/43 - Core: Fix caching behavior for user role cache. Fixes internal error after adding user.
- 09/46 - Core: Improve layout of PaperEntryPage and ResultPanel
- 09/47 - Core/Public: Fix sort order of papers when paging through the paper detail pages
- Fixed adding/removing papers from newsletters


[[v0.9.0]]
== {url-tree}scipamato-0.9.0[0.9.0] -- 2018-09-09

{url-cl}scipamato-0.8.9++...++scipamato-0.9.0[Full Changelog]

.Added
- 09/41 - Public: Include configuration for commercial font IcoMoon
- 09/43 - Core: Allow users to modify their user record including password
- 09/43 - Core: Allow admins to manage user accounts and their roles

.Changed
- Bumped wicket-spring-boot-starter, wicket-bootstrap
- 09/45 - Public: BootstrapMultiselect configurable to switch from 'contains'
                  to 'startsWith/begins' search strategy (wicket-bootstrap-2.0.3)
- Use LocalDateTextField now bundled with wicket-bootstrap-2.0.3

.Fixed
- 09/49 - Core: Fix Summary Report - reset swapped fields
- 09/50 - Core: Fix parsing of location of aheadOfPrint Pubmed studies

.Security
- Viewers to access only PaperListPage/PaperEditPage

[[v0.8.9]]
== {url-tree}scipamato-0.8.9[0.8.9] -- 2018-08-30

{url-cl}scipamato-0.8.8++...++scipamato-0.8.9[Full Changelog]


.Added
- 08/50 - Public: Referential integrity constraints - where possible
- 08/45 - Core: Manage the Newsletter Topics
- 08/56: Synchronize languages from core to public
- 08/56: Implement pseudo-foreign-key-constraint logic for composite keys in SciPaMaTo-Public
- 08/58 - Core: Added ability to sort the newsletter topics + synchronize to SciPaMaTo-Public
- 08/61 - Core: Added validator checking for existing records with DOI or PM_ID assigned
- 08/60 - Public: List of new studies from previous newsletters on NewStudyListPage, as well
          as a list of links requested for by the customer (maintained in database)
- 08/65 - Public: Enable zapping through papers of a newsletter from within detail page

.Changed
- Bump dependencies: jOOQ, spring-cloud, assertj, jasperreports, asm, byte-buddy, commons-lang3
  maven-compiler-plugin, jacoco-maven-plugin
- Core: Collapsible Menu entries with submenu items
- 08/52 - Core: Raise default session timeout from 30 to 60 minutes. Separate cookie names
- 08/54: When synching from Core to Public: Use Kurzerfassungs-fields if main fields are missing
- Core -> Public: Increased the chunk sizes of some sync jobs
- 08/62: Enable switching locale of SciPaMaTo-Public from CMS when shown in iframe

.Fixed
- 08/49 - Core: Do not allow two newsletters in status WIP
- 08/59 - Core: Allow searching for missing years w/ or w/o equal sign (="" or "")
- Wiki: Implemented review suggestions by Zoë Roth
- Core to Public Sync: Fix logging of Housekeeper Job


[[v0.8.8]]
== {url-tree}scipamato-0.8.8[0.8.8] -- 2018-08-06

{url-cl}scipamato-0.8.7++...++scipamato-0.8.8[Full Changelog]

.Fixed
- 08/47: Fix Layout of scipamato page to avoid a cut button in scipamato public when shown in an iframe


[[v0.8.7]]
== {url-tree}scipamato-0.8.7[0.8.7] -- 2018-08-03

{url-cl}scipamato-0.8.6++...++scipamato-0.8.7[Full Changelog]

.Changed
- Bumped dependencies: spring-boot-starter-parent, jOOQ, Flyway, lombok, jOOL, mockito,
  equalsverifier, spring-boot-admin, postgres jdbc driver, bytebuddy, commons-collections4
- Move from org.jooq.jool to org.jooq.jool-java-8

.Fixed
- Fix package name for wicketstuff annotation scan package name
- Fix commercial font usage: fix filtering of css resources
- 08/43: Public: Fix loading public paper details by number, e.g. /paper/number/1234
- Core: Sort Newsletter Topics alphabetically in Paper Editor


[[v0.8.6]]
== {url-tree}scipamato-0.8.6[0.8.6] -- 2018-07-02

{url-cl}scipamato-0.8.5++...++scipamato-0.8.6[Full Changelog]

.Changed
- Migrated to Java 10, Spring Boot 2.0.3 and Apache Wicket 8.0.0
- Bump other dependencies: wicket-spring-boot-starter-parent, wicket-bootstrap, jOOQ, flyway, mockito,spring-boot-starter-admin
- Improved the javadoc: warnings eliminated, javadoc for classes generated by jOOQ and jaxb skipped
- Optimizd confguration of maven-resource-plugin
- Avoided printing stack-trace to the log in case of missing network for Pubmed access
- Explicit data source configuration in core web module
- Renamed ScipamatoApplication to ScipamatoCoreApplication

.Fixed
- Renamed UserDetailService to UserDetailsService
- Have spring batch use the batchDataSource


[[v0.8.5]]
== {url-tree}scipamato-0.8.5[0.8.5] -- 2018-06-15

{url-cl}scipamato-0.8.4++...++scipamato-0.8.5[Full Changelog]

.Added
- 08/08 - Core: Add/Maintain Newsletter. Assign/remove papers to/from newsletter. Search by newsletter attributes
- 08/22 - Public: Added referential integrity constraints between codes and code_classes
- 08/35 - Core/Public: New Studies: Manage newsletters in Core, assign papers with topics. Syncronize to Public (new studies)

.Changed
- 08/23 - Core: Re-extracted scipamato-core-logic that is needed for the migration tool (not part of the open-source aspect of scipamato)
- Bump dependencies: Spring Boot starter, jOOQ, lombok, flyway, jasperreports, mockito, assertj, equalsverifier, jacoco-maven-plugin
- 08/36 - Public: Open paper detail page from new-study page in separate browser tab

.Fixed
- JooqReadOnlyRepo implementations use the record to entity mappers also for the find methods


[[v0.8.4]]
== {url-tree}scipamato-0.8.4[0.8.4] -- 2018-04-18

{url-cl}scipamato-0.8.3++...++scipamato-0.8.4[Full Changelog]

.Changed
- Upgraded dependencies: spring-boot-parent
- Switched from Eclipse to IntelliJ IDEA as IDE. Fixed many issues warned about by the IDE

.Fixed
- 08/12 - Core: Fix startup of SciPaMaTo-Core (introduced in 0.7.3 - commit be8407bfbb4572ef6f3fdddaf024ab0116e7e07b)
- 08/24 - Public: Fix sorting of result table


[[v0.8.3]]
== {url-tree}scipamato-0.8.3[0.8.3] -- 2018-04-06

{url-cl}scipamato-0.8.2++...++scipamato-0.8.3[Full Changelog]

.Changed
- dependency bumps: wicket-spring-boot, jOOQ, PostgreSQL JDBC Driver, spring-cloud
- 08/20 - Public: reduce columns/column sizes in result view (abbreviated
  authors, journal instead of location)
- 08/12 - Public: Add https://blog.apps.npr.org/pym.js/[pym.js] to support
  loading SciPaMaTo-Public within a responsive iframe
- 08/21 - Public: Styling of  NewStudy page


[[v0.8.2]]
== {url-tree}scipamato-0.8.2[0.8.2] -- 2018-03-15

{url-cl}scipamato-0.8.1++...++scipamato-0.8.2[Full Changelog]

.Fixed
- 08/17 - Public: Fix Internal Error when opening papers with Numbers that don't exist as IDs
- 08/18 - Public: Link from NewStudyPage to PublicPage opens in new browser tab


[[v0.8.1]]
== {url-tree}scipamato-0.8.1[0.8.1] -- 2018-03-14

{url-cl}scipamato-0.8.0++...++scipamato-0.8.1[Full Changelog]

.Changed
- 07/65 - Public: Searching with PubYearFrom w/o PubYearUntil only finds papers with the exact PubYear
                  (not anymore PubYear >= PubYearFrom).
                  PubYearUntil w/ empty PubYearFrom still finds papers with PubYear <= PubYearUntil
- Wiki Updates (Public Filtering)

.Fixed
- 07/62 - Public: Adjust the german label/title for clearing the search on PublicPaperPage
- 07/66 - Public: Fix jumping back from DetailPage to NewStudy Page if called from there
- 08/16 - Wicket-Filestore issue probably due to same location for core and public


[[v0.8.0]]
== {url-tree}scipamato-0.8.0[0.8.0] -- 2018-03-13

{url-cl}scipamato-0.7.7++...++scipamato-0.8.0[Full Changelog]

.Added
- 08/13 - Public: Add page with new study (with stubbed data for now)

.Changed
- Dependency updates: wicket-bootstrap


[[v0.7.7]]
== {url-tree}scipamato-0.7.7[0.7.7] -- 2018-03-09

{url-cl}scipamato-0.7.6++...++scipamato-0.7.7[Full Changelog]

.Added
- 07/62 - Public: New Button to clear the search criteria

.Changed
- 07/41 - Public: Increase base font size from 13 px to 15 px
- 07/56 - Public: Repeat the simple search fields in Extended Search
- 07/64 - Public: Provide possibility to quote text search terms (e.g. authors)

.Removed
- 07/04 - Public: Remove ability to search by id/number


[[v0.7.6]]
== {url-tree}scipamato-0.7.6[0.7.6] -- 2018-03-07

{url-cl}scipamato-0.7.5++...++scipamato-0.7.6[Full Changelog]

.Added
- Added customized sonar quality profile used for SciPaMaTo
- Added customized look and feel for scipamato-public based on todc-bootstrap. With optional MetaOT-Font
  which is commercial

.Changed
- Updated screenshots sonar + architecture
- Updated dependencies: wicket, jOOQ, flyway, mockito, spring-cloud, equalsverifier, assertJ
- Improved some topics according to Effective Java, 3rd edition
- Navbar in SciPaMaTo-Public: Do not show by default. Can be overridden via page parameter showNavbar.
  Default state is configurable via property scipamato.navbar-visible-by-default
- Navbar: Do not fix it to top (Position.STATIC-TOP)
- Page Title: use brand instead of hardcoding it

.Fixed
- Amend sonar quality profile and fix some issues highlighted by sonar (mostly serializable related)


[[v0.7.5]]
== {url-tree}scipamato-0.7.5[0.7.5] -- 2018-02-05

{url-cl}scipamato-0.7.4++...++scipamato-0.7.5[Full Changelog]

.Added
- Added structure101 configuration to project both for studio and workspace

.Changed
- architectural refactorings to remove dependency cycles (tangles) both on class and package level
- keep generated pubmed-api classes strictly within scipamato-core-pubmed-api
- have infinitest ignore integration tests
- renamed public packages from ch.difty.scipamato.public_ to ch.difty.scipamato.publ
- updated spring-boot-starter-parent, postgresql jdbc driver, spring-boot-admin

.Removed
- jOOQ related classes copied from spring-boot (https://github.com/spring-projects/spring-boot/issues/11324)


[[v0.7.4]]
== {url-tree}scipamato-0.7.4[0.7.4] -- 2018-01-19

{url-cl}scipamato-0.7.3++...++scipamato-0.7.4[Full Changelog]

.Changed
- Updated jOOQ, jasperreports, spring-cloud, flyway
- 07/47: Correctly add the maven wrapper

.Fixed
- Fixed logging configuration to not write into /tmp


[[v0.7.3]]
== {url-tree}scipamato-0.7.3[0.7.3] -- 2018-01-14

{url-cl}scipamato-0.7.2++...++scipamato-0.7.3[Full Changelog]

.Added
- Test Coverage of untested parts of SciPaMaTo

.Changed
- Switched from GPLv3 to BSD3 license
- CodeStyle: Adjusted code style based on review by Prof. Dierk König.
  Added Eclipse formatter to project.
- Integrated classes of scipamato-common-config and scipamato-core-logic
  into other modules to (slightly) reduce number of maven modules.
  Based on review by Prof. Dierk König.
- Renamed DefaultAuthorParser to PubmedAuthorParser
- Improved JavaDoc for author strings, highlighted dependency on author parser strategy
  and current limitation with JSR303 validation of author strings.
- Updated jOOQ, flyway, lombok, jasperreports, assertJ, jacoco-maven-plugin
- Switched to mockito-2

.Fixed
- AuthorParser: Don't let streams escape their context. Based on review by Prof. Dierk König.
- Do not run the data synchronization from core to public during the nightly build (profile-sonar)
- A few minor so far non-surfacing bugs showing up when working on the test-coverage :-)
- A few imprecise repo methods that started failing with lombok-1.16.20


[[v0.7.2]]
== {url-tree}scipamato-0.7.2[0.7.2] -- 2017-12-22

{url-cl}scipamato-0.7.1++...++scipamato-0.7.2[Full Changelog]

.Changed
- 07/44: Use @ConfigurationProperties to define custom properties
- Version bump: spring-boot-admin-starter-client

.Fixed
- Explicitly manage the bootstrap version (3.3.7-1) that was overridden by spring-cloud-dependencies to 3.2.0

.Security
- Public 07/43: https configuration. Allow referencing SciPaMaTo-Public from iframe. Redirect from http


[[v0.7.1]]
== {url-tree}scipamato-0.7.1[0.7.1] -- 2017-12-13

{url-cl}scipamato-0.7.0++...++scipamato-0.7.1[Full Changelog]

.Added
- QuickStart guide Wiki page

.Changed
- Improved DeveloperInformation and Operations Wiki pages
- Improved DataSource/HikariCP configuration and added tests
- Switched to implicit constructor injection as of spring 4.3

.Fixed
- 07/30: Do not synchronize null int/long columns as 0 (PublicationYear, PM_ID++...++)
- 07/25: Code-Synchronization: Don't synchronize internals, aggregate 5A/B/C to 5abc


[[v0.7.0]]
== {url-tree}scipamato-0.7.0[0.7.0] -- 2017-12-09

{url-cl}scipamato-0.6.3++...++scipamato-0.7.0[Full Changelog]

.Added
- Public: 07/01: Add table paper and two sample records. Simple filter in public GUI to retrieve and display the data from database.
- Public: 07/03: Allow to filter by collective code groups Population (Children vs. Adults) and/or StudyType (Experimental, Epidemiological or Methodology)
- Public: 07/04: Searching by paper number
- Public: 07/05: Detail Page when clicking on the title of a paper in the overview list (same fields as Summary PDF)
- Public: 07/09: External link in detail view pointing to the PubMed site of the related paper
- Public: 07/14: Rest-like URL using the paper number with bookmarkable links (e.g. http://localhost:8081/paper/number/2) that can be used e.g. in newsletters
- Public: 07/24: Allow filtering by Codes
- 07/13: Synchronize Papers, Codes and CodeClasses from SciPaMaTo-Core to SciPaMaTo-Public

.Changed
- Core: 06/21+24: Open external links (to the ChangeLog or wiki pages) in new browser tab
- Story 07/01: New maven modules scipamato-common-entity, scipamato-common-persistence-api, scipamato-common-persistence-jooq
- Documentation updates
- pom refactoring and cleanup
- Small refactorings and improvements
- Version bump: spring-boot-parent, jOOQ, Flyway, commons-lang3, equalsverifier, sonar-maven-plugin
- The link to the change log points to the current version directly

NOTE: Switching to flyway 5.x brings with it a rename of the flyway meta table (from `schema_version` to `flyway_schema_history`). While
current versions of flyway can deal with the old table name, this fallback will be dropped in flyway 6.x. I recommend you to manually rename
the table in your database instances (`alter table schema_version rename to flyway_schema_history;`).


.Removed
- obsolete jOOQ configuration classes. Simplified jOOQ configuration based on spring boot auto-configuration

.Fixed
- Fixed and improved transaction handling in integration tests
- 07/20: Do not automatically run AdHocTests (PubmedXmlServiceIntegrationAdHocTest accessing PubMed over the internet)

.Security
- Public: 07/16: Add spring-security to SciPaMaTo-Public: Anonymous login for the page, required login for actuator endpoints

[[v0.6.3]]
== {url-tree}scipamato-0.6.3[0.6.3] -- 2017-11-06

{url-cl}scipamato-0.6.2++...++scipamato-0.6.3[Full Changelog]

.Changed
- Updated jaxb-api, jasper-reports, spring-cloud-starter-feign, assertJ, JUnitParams
- pom refactoring

.Fixed
- Bug 06/22: Fixes the exception we had after clicking on a freshly imported pubmed paper.
- Bug 06/23: Include new format for collective authors in the author validation.
- Bug 06/27: Fix layout issues with XmlPasteModal panel (Caption, initial size)
- Bug 06/27: When the XMlPasteModal was opened and closed, it could not be opened again without page refresh


[[v0.6.2]]
== {url-tree}scipamato-0.6.2[0.6.2] -- 2017-11-01

{url-cl}scipamato-0.6.1++...++scipamato-0.6.2[Full Changelog]

.Added
- new maven modules scipamato-wicket and scipamato-public with minimal functionality
- Feature 06/21: Add Menu Link to the github wiki page (Help)
- Feature 06/24: Add Menu Link with build version number pointing to the CHANGELOG document on github

.Changed
- Improved documentation and code coverage
- Updated to spring-boot-1.5.8, wicket-7.9.0, bumped wicket-spring-boot-starter, jOOQ-3.10.1, feign

.Fixed
- Fix version alignment between different modules for jOOQ and the postgresql jdbc driver
- Selective improvements with Eclipse Clean-up functionality
- Bug 06/23: Parsing Authors from PubmedXml: Delimiter between normal authors and authors with CollectiveName needs to be semicolon.
- Bug 06/22: PaperListPage: Refresh ResultPanel after having imported via XML from PubMed to immediately show the updated paper list.


[[v0.6.1]]
== {url-tree}scipamato-0.6.1[0.6.1] -- 2017-09-20

{url-cl}scipamato-0.6.0++...++scipamato-0.6.1[Full Changelog]

.Added
- 6/12: enable caching (ehcache3) for static reference data

.Changed
- 6/17: Transformed the project to a maven multi-module project, allowing to reuse author parsing in the data migration project
- pom cleanup
- Introduced Project Lombok for Getters/Setters, Equals/HashCode and Builders
- Rebased the database creation scripts. Now not adding papers or searches anymore, only reference data
- switched from markdown to asciidoc for wiki pages
- Created ChangeLog according to https://keepachangelog.com/en/1.0.0/[Keep a Changelog]
- use OktHttp with feign
- various improvements in wiki pages, javadoc, sonar suggested code changes
- dependency updates: spring-boot-starter, wicket, wicket-spring-boot-starter, jOOQ, postgres-jdbc-driver, spring-boot-admin, assertJ
- Spring batch project for the migration of the legacy data into SciPaMaTo (separate project)

.Fixed
- 6/13: Fix behavior when accessing PubMed without network access
- 6/11: Codes/CodeClasses were not translated according to browser locale
- fix jooq-codegen-maven-plugin after having flyway populate an empty db
- minor architectural improvements (remove dependencies across layers)
- Wiki: Fix description of string searches
- Fixed First Author Parsing from Author string in case of Junior (Jr) after initials


[[v0.6.0]]
== {url-tree}scipamato-0.6.0[0.6.0] -- 2017-07-17

{url-cl}scipamato-0.5.6++...++scipamato-0.6.0[Full Changelog]

.Added
- 6/7: Drag and drop import of PubmedXML (using DropZoneUpload)

.Changed
- improvements in wiki pages, raised test coverage
- dependency updates (jasperreports)

.Fixed
- 6/6: fix upload for attachments > 1MB (now limited to 10MB)


[[v0.5.6]]
== {url-tree}scipamato-0.5.6[0.5.6] -- 2017-07-03

{url-cl}scipamato-0.5.5++...++scipamato-0.5.6[Full Changelog]

.Added
- 5/26: Optimistic locking

.Fixed
- 5/41: fix internal error when clicking save


[[v0.5.5]]
== {url-tree}scipamato-0.5.5[0.5.5] -- 2017-07-02

{url-cl}scipamato-0.5.4++...++scipamato-0.5.5[Full Changelog]

.Added
- 5/38: Short Summary PDF (Kurzerfassung)

.Changed
- using undertow instead of tomcat
- Replace AjaxTimerBehavior with SelfUpdateEvent behavior for id, created, modified
- Use the number instead of (DB) id in the names of the pdf files
- several updates in wiki pages, javadoc, sonar code improvements


[[v0.5.4]]
== {url-tree}scipamato-0.5.4[0.5.4] -- 2017-06-28

{url-cl}scipamato-0.5.3++...++scipamato-0.5.4[Full Changelog]

.Added
- 5/36: Improved exclusion handling (exclude/re-include directly out of paper. Icon)

.Changed
- 5/37: do not switch the label when toggling searchExclusion checkbox
- 5/30: Visual appearance of navigation buttons
- wiki page updates
- dependency update: spring-boot-admin

.Fixed
- 5/35: Validator for codeclass1 should not trigger in search mode



[[v0.5.3]]
== {url-tree}scipamato-0.5.3[0.5.3] -- 2017-06-25

{url-cl}scipamato-0.5.2++...++scipamato-0.5.3[Full Changelog]

.Added
- 5/9: Adding attachments to papers

.Changed
- wiki page updates, sonar code improvements

.Fixed
- Codes were not loaded properly when loading papers by number or pmid
- LinkIconPanel fix


[[v0.5.2]]
== {url-tree}scipamato-0.5.2[0.5.2] -- 2017-06-19

{url-cl}scipamato-0.5.1++...++scipamato-0.5.2[Full Changelog]

.Added
- 5/30: Allow excluding papers from PaperEntryPage
- 5/31: Jump back from PaperEntryPage to either PaperListPage or PaperSearchPage, depending from where we called the page

.Changed
- wiki page updates, javadoc fixes, German translation updates, sonar code improvements
- dependency update: wicket-bootstrap

.Fixed
- 5/29: Search exclusions were not saved in searches
- Layout fixes


[[v0.5.1]]
== {url-tree}scipamato-0.5.1[0.5.1] -- 2017-06-15

{url-cl}scipamato-0.5.0++...++scipamato-0.5.1[Full Changelog]

.Added
- 5/28: Navigation through the different papers in the search result

.Changed
- wiki page updates, javadoc fixes
- dependency updates: spring-boot-starter, spring-boot-admin, spring-cloud-starter-feign

.Fixed
- NPE with Pubmed retrieval with null PMID


[[v0.5.0]]
== {url-tree}scipamato-0.5.0[0.5.0] -- 2017-06-09

{url-cl}scipamato-0.4.5++...++scipamato-0.5.0[Full Changelog]

.Added
- added spring-boot-admin-starter-client

.Changed
- dependency updates: wicket, wicket-bootstrap

.Removed
- 5/21: Dropped H2 support -> sticking with PostgreSQL only for now


[[v0.4.5]]
== {url-tree}scipamato-0.4.5[0.4.5] -- 2017-06-01

{url-cl}scipamato-0.4.4++...++scipamato-0.4.5[Full Changelog]

.Changed
- dependency updates: postgres-jdbc, jOOQ, flyway, feign-jaxb, JUnitParams, jaxb2-maven-plugin
- wiki page updates, javadoc improvements
- minor refactorings

.Fixed
- Fix keeping the different 'new field' instances synchronized in the web page


[[v0.4.4]]
== {url-tree}scipamato-0.4.4[0.4.4] -- 2017-05-11

{url-cl}scipamato-0.4.3++...++scipamato-0.4.4[Full Changelog]

.Changed
- Test release from jenkins


[[v0.4.3]]
== {url-tree}scipamato-0.4.3[0.4.3] -- 2017-05-11

{url-cl}scipamato-0.4.2++...++scipamato-0.4.3[Full Changelog]

.Added
- Releasing the project with the jenkins release job


[[v0.4.2]]
== {url-tree}scipamato-0.4.2[0.4.2] -- 2017-05-10

{url-cl}scipamato-0.4.1++...++scipamato-0.4.2[Full Changelog]

.Added
- new business id (Number), which is different from the sequence backed database id
- Import data from pubmed with only the PmID entered
- Paper Entry Page: Separate tab for 'new fields'
- Make the PostgreSQL backend the first class member while currently still supporting the H2 backend (supporting the prototyping, not for support.)
- Flyway for database migrations

.Changed
- dependency updates
- wiki page updates

.Deprecated
- H2 support

.Removed
- Removed dummy home page
- Removed spring-data


[[v0.4.1]]
== {url-tree}scipamato-0.4.1[0.4.1] -- 2017-03-11

{url-cl}scipamato-0.4.0++...++scipamato-0.4.1[Full Changelog]

.Added
- Added License: GPLv3

.Changed
- refactorings and code cleanup
- wiki page updates


[[v0.4.0]]
== {url-tree}scipamato-0.4.0[0.4.0] -- 2017-02-23

{url-cl}scipamato-0.3.5++...++scipamato-0.4.0[Full Changelog]

.Added
- First shot at parsing, importing from and comparing SiPaMaTo content with PubMed articles based on PMID. Working with Pubmed XML file exports. Direct API call to PubMed in order to compare common fields.

.Changed
- sonar code improvements
- improved test coverage


[[v0.3.5]]
== {url-tree}scipamato-0.3.5[0.3.5] -- 2017-02-08

{url-cl}scipamato-0.3.4++...++scipamato-0.3.5[Full Changelog]

.Added
- Searching by created/last modified
- Manage SciPaMaTo with Jenkins CI

.Changed
- Replace AutoSaveBehavior with direct ajax saves
- wiki page updates

.Fixed
- small bug fixes


[[v0.3.4]]
== {url-tree}scipamato-0.3.4[0.3.4] -- 2017-02-01

{url-cl}scipamato-0.3.3++...++scipamato-0.3.4[Full Changelog]

.Changed
- Implemented various feed-back items from users
- git commit-id-plugin to show repo information in actuator
- wiki page updates, javadoc updates
- dependency updates: spring-boot-starter-parent


[[v0.3.3]]
== {url-tree}scipamato-0.3.3[0.3.3] -- 2017-01-29

{url-cl}scipamato-0.3.2++...++scipamato-0.3.3[Full Changelog]

.Added
- additional PDF reports

.Fixed
- small fixes


[[v0.3.2]]
== {url-tree}scipamato-0.3.2[0.3.2] -- 2017-01-25

{url-cl}scipamato-0.3.1++...++scipamato-0.3.2[Full Changelog]

.Added
- PDF reports
- additional test data

.Changed
- Do not set the publication year in new papers
- maintain users in the database
- wiki page updates, layout improvements
- dependency updates: wicketstuff-annotation, wicket-spring-boot-starter,jOOQ

.Fixed
- fix paging the papers in the list view
- Layout/translation fixes based on user feedback


[[v0.3.1]]
== {url-tree}scipamato-0.3.1[0.3.1] -- 2017-01-06

{url-cl}scipamato-0.3.0++...++scipamato-0.3.1[Full Changelog]

.Added
- new field for paper: 'original abstract'

.Fixed
- Fix search term evaluation


[[v0.3.0]]
== {url-tree}scipamato-0.3.0[0.3.0] -- 2017-01-06

{url-cl}scipamato-0.2.0++...++scipamato-0.3.0[Full Changelog]

.Added
- Show a papers creator/last modifying user

.Changed
- layout adjustments in paper entry page
- wiki page updates
- dependency updates: spring-boot-starter, jOOQ, wicket


[[v0.2.0]]
== {url-tree}scipamato-0.2.0[0.2.0] -- 2016-12-15

{url-cl}scipamato-0.1.0++...++scipamato-0.2.0[Full Changelog]

.Added
- Complex search capability
- Exclude papers found in searches
- refactor and cleanup
- small bug fixes
- dependency updates


[[v0.1.0]]
== [0.1.0] -- 2016-11-05

.Added
- bootstrap the whole project
- list, show and edit papers
