= Changelog
Urs Joss <urs.joss@gmx.ch>
:icons: font
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

All notable changes to this project will be documented in this file.

== Format and Versioning Scheme

The format is based on http://keepachangelog.com/en/1.0.0/[Keep a Changelog].

The versioning scheme in the pre-1.0.0 versions is _not_ adhering to http://semver.org/spec/v2.0.0.html[Semantic Versioning].

Given a version number 0.ITERATION.RELEASE, we're incrementing

. ITERATION version matching the project iteration
. RELEASE version with every release within the given iteration.

TIP: E.g. release 0.5.6 is the 6th release in iteration number 5.


I will most probably switch to semantic versioning after having reached release 1.0.0.

NOTE: References to user stories are in the form Iteration/Story-Number.

////

[[v0.0.0]]
== [0.0.0] -- 2018-00-00

.Added

.Changed

.Deprecated

.Removed

.Fixed

.Security

////

[[unreleased]]
== [unreleased]

.Added

- 09/10 - Public: Allow filtering by keywords

.Changed
- Bumped dependencies: flyway, byte-buddy, commons-lang3, mockito

.Deprecated

.Removed

.Fixed
- 09/67 - Core: Remove obsolete newsletter topics from sort list
- 09/74 - Core: Prevent double clicks on buttons and disable save button until auto-save completed
- Update dependencies spring-boot-parent, equalsverifier, wicket-jquery-ui, byte-buddy, jaxb-api, jaxb-impl, jaxb-runtime
  spring-boot-starter-admin-client

.Security


[[v0.9.2]]
== [0.9.2] -- 2018-10-03

.Changed
- Updated dependencies wicket, wicketstuff, wicket-bootstrap
- 09/64 - Core: Prepend the first word of the brand to the number label in the edit page
- 09/63 - Core: Make newPaper button in PaperListPage more distinguishable (Type Primary)
- 09/57 - Core: Do alert if Original Abstract differs between Pubmed and SciPaMaTo. Normalize line ends before comparing
- 09/72 - Core: Add newly created paper to head of id list for moving back and forth (after first save)

.Fixed
- Maximum Upload File Size correctly reset to 10M
- 09/57 - Core: Fix Pubmed import from file for certain html tags in text
                Not fixed for direct import from pubmed! (new dtd can't be parsed by jaxb)
- 09/59 - Core -> Public: Make sync more resilient by basing the sync on number instead of id


[[v0.9.1]]
== [0.9.1] -- 2018-09-17

.Added
- Public: French translation of the PublicPaperDetailPage
- 09/56 - Core: Access Pubmed using api_key if configured

.Changed
- Bumped dependency versions: spring-boot-starter, jOOQ, mockito, byte-buddy, equalsverifier, sonar-maven-plugin

.Fixed
- 09/43 - Core: Fix caching behavior for user role cache. Fixes internal error after adding user.
- 09/46 - Core: Improve layout of PaperEntryPage and ResultPanel
- 09/47 - Core/Public: Fix sort order of papers when paging through the paper detail pages
- Fixed adding/removing papers from newsletters


[[v0.9.0]]
== [0.9.0] -- 2018-09-09

.Added
- 09/41 - Public: Include configuration for commercial font IcoMoon
- 09/43 - Core: Allow users to modify their user record including password
- 09/43 - Core: Allow admins to manage user accounts and their roles

.Changed
- Bumped wicket-spring-boot-starter, wicket-bootstrap
- 09/45 - Public: BootstrapMultiselect configurable to switch from 'contains'
                  to 'startsWith/begins' search strategy (wicket-bootstrap-2.0.3)
- Use LocalDateTextField now bundled with wicket-bootstrap-2.0.3

.Fixed
- 09/49 - Core: Fix Summary Report - reset swapped fields
- 09/50 - Core: Fix parsing of location of aheadOfPrint Pubmed studies

.Security
- Viewers to access only PaperListPage/PaperEditPage

[[v0.8.9]]
== [0.8.9] -- 2018-08-30

.Added
- 08/50 - Public: Referential integrity constraints - where possible
- 08/45 - Core: Manage the Newsletter Topics
- 08/56: Synchronize languages from core to public
- 08/56: Implement pseudo-foreign-key-constraint logic for composite keys in SciPaMaTo-Public
- 08/58 - Core: Added ability to sort the newsletter topics + synchronize to SciPaMaTo-Public
- 08/61 - Core: Added validator checking for existing records with DOI or PM_ID assigned
- 08/60 - Public: List of new studies from previous newsletters on NewStudyListPage, as well
          as a list of links requested for by the customer (maintained in database)
- 08/65 - Public: Enable zapping through papers of a newsletter from within detail page

.Changed
- Bump dependencies: jOOQ, spring-cloud, assertj, jasperreports, asm, byte-buddy, commons-lang3
  maven-compiler-plugin, jacoco-maven-plugin
- Core: Collapsible Menu entries with submenu items
- 08/52 - Core: Raise default session timeout from 30 to 60 minutes. Separate cookie names
- 08/54: When synching from Core to Public: Use Kurzerfassungs-fields if main fields are missing
- Core -> Public: Increased the chunk sizes of some sync jobs
- 08/62: Enable switching locale of SciPaMaTo-Public from CMS when shown in iframe

.Fixed
- 08/49 - Core: Do not allow two newsletters in status WIP
- 08/59 - Core: Allow searching for missing years w/ or w/o equal sign (="" or "")
- Wiki: Implemented review suggestions by Zoë Roth
- Core to Public Sync: Fix logging of Housekeeper Job


[[v0.8.8]]
== [0.8.8] -- 2018-08-06

.Fixed
- 08/47: Fix Layout of scipamato page to avoid a cut button in scipamato public when shown in an iframe


[[v0.8.7]]
== [0.8.7] -- 2018-08-03

.Changed
- Bumped dependencies: spring-boot-starter-parent, jOOQ, Flyway, lombok, jOOL, mockito,
  equalsverifier, spring-boot-admin, postgres jdbc driver, bytebuddy, commons-collections4
- Move from org.jooq.jool to org.jooq.jool-java-8

.Fixed
- Fix package name for wicketstuff annotation scan package name
- Fix commercial font usage: fix filtering of css resources
- 08/43: Public: Fix loading public paper details by number, e.g. /paper/number/1234
- Core: Sort Newsletter Topics alphabetically in Paper Editor


[[v0.8.6]]
== [0.8.6] -- 2018-07-02

.Changed
- Migrated to Java 10, Spring Boot 2.0.3 and Apache Wicket 8.0.0
- Bump other dependencies: wicket-spring-boot-starter-parent, wicket-bootstrap, jOOQ, flyway, mockito,spring-boot-starter-admin
- Improved the javadoc: warnings eliminated, javadoc for classes generated by jOOQ and jaxb skipped
- Optimizd confguration of maven-resource-plugin
- Avoided printing stack-trace to the log in case of missing network for Pubmed access
- Explicit data source configuration in core web module
- Renamed ScipamatoApplication to ScipamatoCoreApplication

.Fixed
- Renamed UserDetailService to UserDetailsService
- Have spring batch use the batchDataSource


[[v0.8.5]]
== [0.8.5] -- 2018-06-15


.Added
- 08/08 - Core: Add/Maintain Newsletter. Assign/remove papers to/from newsletter. Search by newsletter attributes
- 08/22 - Public: Added referential integrity constraints between codes and code_classes
- 08/35 - Core/Public: New Studies: Manage newsletters in Core, assign papers with topics. Syncronize to Public (new studies)

.Changed
- 08/23 - Core: Re-extracted scipamato-core-logic that is needed for the migration tool (not part of the open-source aspect of scipamato)
- Bump dependencies: Spring Boot starter, jOOQ, lombok, flyway, jasperreports, mockito, assertj, equalsverifier, jacoco-maven-plugin
- 08/36 - Public: Open paper detail page from new-study page in separate browser tab

.Fixed
- JooqReadOnlyRepo implementations use the record to entity mappers also for the find methods


[[v0.8.4]]
== [0.8.4] -- 2018-04-18

.Changed
- Upgraded dependencies: spring-boot-parent
- Switched from Eclipse to IntelliJ IDEA as IDE. Fixed many issues warned about by the IDE

.Fixed
- 08/12 - Core: Fix startup of SciPaMaTo-Core (introduced in 0.7.3 - commit be8407bfbb4572ef6f3fdddaf024ab0116e7e07b)
- 08/24 - Public: Fix sorting of result table


[[v0.8.3]]
== [0.8.3] -- 2018-04-06

.Changed
- dependency bumps: wicket-spring-boot, jOOQ, PostgreSQL JDBC Driver, spring-cloud
- 08/20 - Public: reduce columns/column sizes in result view (abbreviated
  authors, journal instead of location)
- 08/12 - Public: Add http://blog.apps.npr.org/pym.js/[pym.js] to support
  loading SciPaMaTo-Public within a responsive iframe
- 08/21 - Public: Styling of  NewStudy page


[[v0.8.2]]
== [0.8.2] -- 2018-03-15

.Fixed
- 08/17 - Public: Fix Internal Error when opening papers with Numbers that don't exist as IDs
- 08/18 - Public: Link from NewStudyPage to PublicPage opens in new browser tab


[[v0.8.1]]
== [0.8.1] -- 2018-03-14

.Changed
- 07/65 - Public: Searching with PubYearFrom w/o PubYearUntil only finds papers with the exact PubYear
                  (not anymore PubYear >= PubYearFrom).
                  PubYearUntil w/ empty PubYearFrom still finds papers with PubYear <= PubYearUntil
- Wiki Updates (Public Filtering)

.Fixed
- 07/62 - Public: Adjust the german label/title for clearing the search on PublicPaperPage
- 07/66 - Public: Fix jumping back from DetailPage to NewStudy Page if called from there
- 08/16 - Wicket-Filestore issue probably due to same location for core and public


[[v0.8.0]]
== [0.8.0] -- 2018-03-13

.Added
- 08/13 - Public: Add page with new study (with stubbed data for now)

.Changed
- Dependency updates: wicket-bootstrap


[[v0.7.7]]
== [0.7.7] -- 2018-03-09

.Added
- 07/62 - Public: New Button to clear the search criteria

.Changed
- 07/41 - Public: Increase base font size from 13 px to 15 px
- 07/56 - Public: Repeat the simple search fields in Extended Search
- 07/64 - Public: Provide possibility to quote text search terms (e.g. authors)

.Removed
- 07/04 - Public: Remove ability to search by id/number


[[v0.7.6]]
== [0.7.6] -- 2018-03-07

.Added
- Added customized sonar quality profile used for SciPaMaTo
- Added customized look and feel for scipamato-public based on todc-bootstrap. With optional MetaOT-Font
  which is commercial

.Changed
- Updated screenshots sonar + architecture
- Updated dependencies: wicket, jOOQ, flyway, mockito, spring-cloud, equalsverifier, assertJ
- Improved some topics according to Effective Java, 3rd edition
- Navbar in SciPaMaTo-Public: Do not show by default. Can be overridden via page parameter showNavbar.
  Default state is configurable via property scipamato.navbar-visible-by-default
- Navbar: Do not fix it to top (Position.STATIC-TOP)
- Page Title: use brand instead of hardcoding it

.Fixed
- Amend sonar quality profile and fix some issues highlighted by sonar (mostly serializable related)


[[v0.7.5]]
== [0.7.5] -- 2018-02-05

.Added
- Added structure101 configuration to project both for studio and workspace

.Changed
- architectural refactorings to remove dependency cycles (tangles) both on class and package level
- keep generated pubmed-api classes strictly within scipamato-core-pubmed-api
- have infinitest ignore integration tests
- renamed public packages from ch.difty.scipamato.public_ to ch.difty.scipamato.publ
- updated spring-boot-starter-parent, postgresql jdbc driver, spring-boot-admin

.Removed
- jOOQ related classes copied from spring-boot (https://github.com/spring-projects/spring-boot/issues/11324)


[[v0.7.4]]
== [0.7.4] -- 2018-01-19

.Changed
- Updated jOOQ, jasperreports, spring-cloud, flyway
- 07/47: Correctly add the maven wrapper

.Fixed
- Fixed logging configuration to not write into /tmp


[[v0.7.3]]
== [0.7.3] -- 2018-01-14

.Added
- Test Coverage of untested parts of SciPaMaTo

.Changed
- Switched from GPLv3 to BSD3 license
- CodeStyle: Adjusted code style based on review by Prof. Dierk König.
  Added Eclipse formatter to project.
- Integrated classes of scipamato-common-config and scipamato-core-logic
  into other modules to (slightly) reduce number of maven modules.
  Based on review by Prof. Dierk König.
- Renamed DefaultAuthorParser to PubmedAuthorParser
- Improved JavaDoc for author strings, highlighted dependency on author parser strategy
  and current limitation with JSR303 validation of author strings.
- Updated jOOQ, flyway, lombok, jasperreports, assertJ, jacoco-maven-plugin
- Switched to mockito-2

.Fixed
- AuthorParser: Don't let streams escape their context. Based on review by Prof. Dierk König.
- Do not run the data synchronization from core to public during the nightly build (profile-sonar)
- A few minor so far non-surfacing bugs showing up when working on the test-coverage :-)
- A few imprecise repo methods that started failing with lombok-1.16.20


[[v0.7.2]]
== [0.7.2] -- 2017-12-22

.Changed
- 07/44: Use @ConfigurationProperties to define custom properties
- Version bump: spring-boot-admin-starter-client

.Fixed
- Explicitly manage the bootstrap version (3.3.7-1) that was overridden by spring-cloud-dependencies to 3.2.0

.Security
- Public 07/43: https configuration. Allow referencing SciPaMaTo-Public from iframe. Redirect from http


[[v0.7.1]]
== [0.7.1] -- 2017-12-13

.Added
- QuickStart guide Wiki page

.Changed
- Improved DeveloperInformation and Operations Wiki pages
- Improved DataSource/HikariCP configuration and added tests
- Switched to implicit constructor injection as of spring 4.3

.Fixed
- 07/30: Do not synchronize null int/long columns as 0 (PublicationYear, PM_ID...)
- 07/25: Code-Synchronization: Don't synchronize internals, aggregate 5A/B/C to 5abc


[[v0.7.0]]
== [0.7.0] -- 2017-12-09

.Added
- Public: 07/01: Add table paper and two sample records. Simple filter in public GUI to retrieve and display the data from database.
- Public: 07/03: Allow to filter by collective code groups Population (Children vs. Adults) and/or StudyType (Experimental, Epidemiological or Methodology)
- Public: 07/04: Searching by paper number
- Public: 07/05: Detail Page when clicking on the title of a paper in the overview list (same fields as Summary PDF)
- Public: 07/09: External link in detail view pointing to the PubMed site of the related paper
- Public: 07/14: Rest-like URL using the paper number with bookmarkable links (e.g. http://localhost:8081/paper/number/2) that can be used e.g. in newsletters
- Public: 07/24: Allow filtering by Codes
- 07/13: Synchronize Papers, Codes and CodeClasses from SciPaMaTo-Core to SciPaMaTo-Public

.Changed
- Core: 06/21+24: Open external links (to the ChangeLog or wiki pages) in new browser tab
- Story 07/01: New maven modules scipamato-common-entity, scipamato-common-persistence-api, scipamato-common-persistence-jooq
- Documentation updates
- pom refactoring and cleanup
- Small refactorings and improvements
- Version bump: spring-boot-parent, jOOQ, Flyway, commons-lang3, equalsverifier, sonar-maven-plugin
- The link to the change log points to the current version directly

NOTE: Switching to flyway 5.x brings with it a rename of the flyway meta table (from `schema_version` to `flyway_schema_history`). While
current versions of flyway can deal with the old table name, this fallback will be dropped in flyway 6.x. I recommend you to manually rename
the table in your database instances (`alter table schema_version rename to flyway_schema_history;`).


.Removed
- obsolete jOOQ configuration classes. Simplified jOOQ configuration based on spring boot auto-configuration

.Fixed
- Fixed and improved transaction handling in integration tests
- 07/20: Do not automatically run AdHocTests (PubmedXmlServiceIntegrationAdHocTest accessing PubMed over the internet)

.Security
- Public: 07/16: Add spring-security to SciPaMaTo-Public: Anonymous login for the page, required login for actuator endpoints

[[v0.6.3]]
== [0.6.3] -- 2017-11-06

.Changed
- Updated jaxb-api, jasper-reports, spring-cloud-starter-feign, assertJ, JUnitParams
- pom refactoring

.Fixed
- Bug 06/22: Fixes the exception we had after clicking on a freshly imported pubmed paper.
- Bug 06/23: Include new format for collective authors in the author validation.
- Bug 06/27: Fix layout issues with XmlPasteModal panel (Caption, initial size)
- Bug 06/27: When the XMlPasteModal was opened and closed, it could not be opened again without page refresh


[[v0.6.2]]
== [0.6.2] -- 2017-11-01
.Added
- new maven modules scipamato-wicket and scipamato-public with minimal functionality
- Feature 06/21: Add Menu Link to the github wiki page (Help)
- Feature 06/24: Add Menu Link with build version number pointing to the CHANGELOG document on github 

.Changed
- Improved documentation and code coverage
- Updated to spring-boot-1.5.8, wicket-7.9.0, bumped wicket-spring-boot-starter, jOOQ-3.10.1, feign

.Fixed
- Fix version alignment between different modules for jOOQ and the postgresql jdbc driver
- Selective improvements with Eclipse Clean-up functionality
- Bug 06/23: Parsing Authors from PubmedXml: Delimiter between normal authors and authors with CollectiveName needs to be semicolon.
- Bug 06/22: PaperListPage: Refresh ResultPanel after having imported via XML from PubMed to immediately show the updated paper list.


[[v0.6.1]]
== [0.6.1] -- 2017-09-20

.Added
- 6/12: enable caching (ehcache3) for static reference data

.Changed
- 6/17: Transformed the project to a maven multi-module project, allowing to reuse author parsing in the data migration project
- pom cleanup
- Introduced Project Lombok for Getters/Setters, Equals/HashCode and Builders
- Rebased the database creation scripts. Now not adding papers or searches anymore, only reference data
- switched from markdown to asciidoc for wiki pages
- Created ChangeLog according to http://keepachangelog.com/en/1.0.0/[Keep a Changelog]
- use OktHttp with feign
- various improvements in wiki pages, javadoc, sonar suggested code changes
- dependency updates: spring-boot-starter, wicket, wicket-spring-boot-starter, jOOQ, postgres-jdbc-driver, spring-boot-admin, assertJ
- Spring batch project for the migration of the legacy data into SciPaMaTo (separate project)

.Fixed
- 6/13: Fix behavior when accessing PubMed without network access
- 6/11: Codes/CodeClasses were not translated according to browser locale
- fix jooq-codegen-maven-plugin after having flyway populate an empty db
- minor architectural improvements (remove dependencies across layers)
- Wiki: Fix description of string searches
- Fixed First Author Parsing from Author string in case of Junior (Jr) after initials


[[v0.6.0]]
== [0.6.0] -- 2017-07-17

.Added
- 6/7: Drag and drop import of PubmedXML (using DropZoneUpload)

.Changed
- improvements in wiki pages, raised test coverage
- dependency updates (jasperreports)

.Fixed
- 6/6: fix upload for attachments > 1MB (now limited to 10MB)


[[v0.5.6]]
== [0.5.6] -- 2017-07-03

.Added
- 5/26: Optimistic locking

.Fixed
- 5/41: fix internal error when clicking save


[[v0.5.5]]
== [0.5.5] -- 2017-07-02

.Added
- 5/38: Short Summary PDF (Kurzerfassung)

.Changed
- using undertow instead of tomcat
- Replace AjaxTimerBehavior with SelfUpdateEvent behavior for id, created, modified
- Use the number instead of (DB) id in the names of the pdf files
- several updates in wiki pages, javadoc, sonar code improvements


[[v0.5.4]]
== [0.5.4] -- 2017-06-28

.Added
- 5/36: Improved exclusion handling (exclude/re-include directly out of paper. Icon)

.Changed
- 5/37: do not switch the label when toggling searchExclusion checkbox
- 5/30: Visual appearance of navigation buttons
- wiki page updates
- dependency update: spring-boot-admin

.Fixed
- 5/35: Validator for codeclass1 should not trigger in search mode



[[v0.5.3]]
== [0.5.3] -- 2017-06-25

.Added
- 5/9: Adding attachments to papers

.Changed
- wiki page updates, sonar code improvements

.Fixed
- Codes were not loaded properly when loading papers by number or pmid
- LinkIconPanel fix


[[v0.5.2]]
== [0.5.2] -- 2017-06-19

.Added
- 5/30: Allow excluding papers from PaperEntryPage
- 5/31: Jump back from PaperEntryPage to either PaperListPage or PaperSearchPage, depending from where we called the page

.Changed
- wiki page updates, javadoc fixes, German translation updates, sonar code improvements
- dependency update: wicket-bootstrap

.Fixed
- 5/29: Search exclusions were not saved in searches
- Layout fixes


[[v0.5.1]]
== [0.5.1] -- 2017-06-15

.Added
- 5/28: Navigation through the different papers in the search result

.Changed
- wiki page updates, javadoc fixes
- dependency updates: spring-boot-starter, spring-boot-admin, spring-cloud-starter-feign

.Fixed
- NPE with Pubmed retrieval with null PMID


[[v0.5.0]]
== [0.5.0] -- 2017-06-09

.Added
- added spring-boot-admin-starter-client

.Changed
- dependency updates: wicket, wicket-bootstrap

.Removed
- 5/21: Dropped H2 support -> sticking with PostgreSQL only for now


[[v0.4.5]]
== [0.4.5] -- 2017-06-01

.Changed
- dependency updates: postgres-jdbc, jOOQ, flyway, feign-jaxb, JUnitParams, jaxb2-maven-plugin
- wiki page updates, javadoc improvements
- minor refactorings

.Fixed
- Fix keeping the different 'new field' instances synchronized in the web page


[[v0.4.4]]
== [0.4.4] -- 2017-05-11

.Changed
- Test release from jenkins


[[v0.4.3]]
== [0.4.3] -- 2017-05-11

.Added
- Releasing the project with the jenkins release job


[[v0.4.2]]
== [0.4.2] -- 2017-05-10

.Added
- new business id (Number), which is different from the sequence backed database id
- Import data from pubmed with only the PmID entered
- Paper Entry Page: Separate tab for 'new fields'
- Make the PostgreSQL backend the first class member while currently still supporting the H2 backend (supporting the prototyping, not for support.)
- Flyway for database migrations

.Changed
- dependency updates
- wiki page updates

.Deprecated
- H2 support

.Removed
- Removed dummy home page
- Removed spring-data


[[v0.4.1]]
== [0.4.1] -- 2017-03-11

.Added
- Added License: GPLv3

.Changed
- refactorings and code cleanup
- wiki page updates


[[v0.4.0]]
== [0.4.0] -- 2017-02-23

.Added
- First shot at parsing, importing from and comparing SiPaMaTo content with PubMed articles based on PMID. Working with Pubmed XML file exports. Direct API call to PubMed in order to compare common fields.

.Changed
- sonar code improvements
- improved test coverage


[[v0.3.5]]
== [0.3.5] -- 2017-02-08

.Added
- Searching by created/last modified
- Manage SciPaMaTo with Jenkins CI

.Changed
- Replace AutoSaveBehavior with direct ajax saves
- wiki page updates

.Fixed
- small bug fixes


[[v0.3.4]]
== [0.3.4] -- 2017-02-01

.Changed
- Implemented various feed-back items from users
- git commit-id-plugin to show repo information in actuator
- wiki page updates, javadoc updates
- dependency updates: spring-boot-starter-parent


[[v0.3.3]]
== [0.3.3] -- 2017-01-29

.Added
- additional PDF reports

.Fixed
- small fixes


[[v0.3.2]]
== [0.3.2] -- 2017-01-25

.Added
- PDF reports
- additional test data

.Changed
- Do not set the publication year in new papers
- maintain users in the database
- wiki page updates, layout improvements
- dependency updates: wicketstuff-annotation, wicket-spring-boot-starter,jOOQ

.Fixed
- fix paging the papers in the list view
- Layout/translation fixes based on user feedback


[[v0.3.1]]
== [0.3.1] -- 2017-01-06

.Added
- new field for paper: 'original abstract'

.Fixed
- Fix search term evaluation


[[v0.3.0]]
== [0.3.0] -- 2017-01-06

.Added
- Show a papers creator/last modifying user

.Changed
- layout adjustments in paper entry page
- wiki page updates
- dependency updates: spring-boot-starter, jOOQ, wicket


[[v0.2.0]]
== [0.2.0] -- 2016-12-15

.Added
- Complex search capability
- Exclude papers found in searches
- refactor and cleanup
- small bug fixes
- dependency updates


[[v0.1.0]]
== [0.1.0] -- 2016-11-05

.Added
- bootstrap the whole project
- list, show and edit papers
