/*
 * Pre-populate the database with static reference data
 */

INSERT INTO code_class VALUES
  (1, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT),
  (2, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT),
  (3, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT),
  (4, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT),
  (5, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT),
  (6, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT),
  (7, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT),
  (8, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);


INSERT INTO code_class_tr VALUES (DEFAULT, 1, 'de', 'Schadstoffe', 'Schadstoffe, Einwirkung, Exposition', DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_class_tr VALUES (DEFAULT, 2, 'de', 'Region', 'Geographie (Europa, andere)', DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_class_tr VALUES (DEFAULT, 3, 'de', 'Kollektiv', 'Stichprobe, Kollektiv', DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_class_tr VALUES (DEFAULT, 4, 'de', 'Zielgrössen', 'Wirkungen, Zielgrössen', DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_class_tr VALUES (DEFAULT, 5, 'de', 'Studientyp', 'Art der Studie, der Publikation', DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_class_tr VALUES (DEFAULT, 6, 'de', 'Spezies', 'Spezies (Mensch, Tier, Pflanze etc.)', DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_class_tr VALUES (DEFAULT, 7, 'de', 'Zeitdauer', 'Zeit der Einwirkung (kurzfristig – langfristig)', DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_class_tr VALUES (DEFAULT, 8, 'de', 'Umgebung', 'Umgebung (berufliche Exposition, Aussenluft…)', DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);

INSERT INTO code_class_tr VALUES (DEFAULT, 1, 'en', 'Exposure Agent', '', DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_class_tr VALUES (DEFAULT, 2, 'en', 'Region', '', DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_class_tr VALUES (DEFAULT, 3, 'en', 'Study Population', '', DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_class_tr VALUES (DEFAULT, 4, 'en', 'Health Outcome', '', DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_class_tr VALUES (DEFAULT, 5, 'en', 'Study Design', '', DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_class_tr VALUES (DEFAULT, 6, 'en', 'Species', '', DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_class_tr VALUES (DEFAULT, 7, 'en', 'Duration of Exposure', '', DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_class_tr VALUES (DEFAULT, 8, 'en', 'Setting', '', DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);

INSERT INTO code_class_tr VALUES (DEFAULT, 1, 'fr', 'Polluant nocif', '', DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_class_tr VALUES (DEFAULT, 2, 'fr', 'Région', '', DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_class_tr VALUES (DEFAULT, 3, 'fr', 'Echantillons des personnes', '', DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_class_tr VALUES (DEFAULT, 4, 'fr', 'Effets physiologigue ou nocifs', '', DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_class_tr VALUES (DEFAULT, 5, 'fr', 'Typ d''étude', '', DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_class_tr VALUES (DEFAULT, 6, 'fr', 'Espèces investigées', '', DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_class_tr VALUES (DEFAULT, 7, 'fr', 'Durée de l''exposition', '', DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_class_tr VALUES (DEFAULT, 8, 'fr', 'Site d''exposition', '', DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);

select setval('code_class_tr_id_seq', max(id)) FROM code_class_tr;

INSERT INTO code VALUES('1F', 1,  1, DEFAULT, 1, '2017-01-01T08:01:33.821', 1, '2017-01-01T08:01:33.821', 1);
INSERT INTO code VALUES('1A', 1,  2, DEFAULT, 1, '2017-01-01T08:01:33.821', 1, '2017-01-01T08:01:33.821', 1);
INSERT INTO code VALUES('1B', 1,  3, DEFAULT, 1, '2017-01-01T08:01:33.821', 1, '2017-01-01T08:01:33.821', 1);
INSERT INTO code VALUES('1C', 1,  4, DEFAULT, 1, '2017-01-01T08:01:33.821', 1, '2017-01-01T08:01:33.821', 1);
INSERT INTO code VALUES('1D', 1,  5, DEFAULT, 1, '2017-01-01T08:01:33.821', 1, '2017-01-01T08:01:33.821', 1);
INSERT INTO code VALUES('1E', 1,  6, DEFAULT, 1, '2017-01-01T08:01:33.821', 1, '2017-01-01T08:01:33.821', 1);
INSERT INTO code VALUES('1G', 1,  7, DEFAULT, 1, '2017-01-01T08:01:33.821', 1, '2017-01-01T08:01:33.821', 1);
INSERT INTO code VALUES('1H', 1,  8, DEFAULT, 1, '2017-01-01T08:01:33.821', 1, '2017-01-01T08:01:33.821', 1);
INSERT INTO code VALUES('1I', 1,  9, DEFAULT, 1, '2017-01-01T08:01:33.821', 1, '2017-01-01T08:01:33.821', 1);
INSERT INTO code VALUES('1K', 1, 10, DEFAULT, 1, '2017-01-01T08:01:33.821', 1, '2017-01-01T08:01:33.821', 1);
INSERT INTO code VALUES('1L', 1, 11, DEFAULT, 1, '2017-01-01T08:01:33.821', 1, '2017-01-01T08:01:33.821', 1);
INSERT INTO code VALUES('1M', 1, 12, DEFAULT, 1, '2017-01-01T08:01:33.821', 1, '2017-01-01T08:01:33.821', 1);
INSERT INTO code VALUES('1N', 1, 13, TRUE   , 1, '2017-01-01T08:01:33.821', 1, '2017-01-01T08:01:33.821', 1);
INSERT INTO code VALUES('1P', 1, 14, DEFAULT, 1, '2017-01-01T08:01:33.821', 1, '2017-01-01T08:01:33.821', 1);
INSERT INTO code VALUES('1R', 1, 15, DEFAULT, 1, '2017-01-01T08:01:33.821', 1, '2017-01-01T08:01:33.821', 1);
INSERT INTO code VALUES('1S', 1, 16, DEFAULT, 1, '2017-01-01T08:01:33.821', 1, '2017-01-01T08:01:33.821', 1);
INSERT INTO code VALUES('1T', 1, 17, DEFAULT, 1, '2017-01-01T08:01:33.821', 1, '2017-01-01T08:01:33.821', 1);
INSERT INTO code VALUES('1U', 1, 18, TRUE   , 1, '2017-01-01T08:01:33.821', 1, '2017-01-01T08:01:33.821', 1);
INSERT INTO code VALUES('1V', 1, 19, DEFAULT, 1, '2017-01-01T08:01:33.821', 1, '2017-01-01T08:01:33.821', 1);
INSERT INTO code VALUES('1Y', 1, 20, DEFAULT, 1, '2017-01-01T08:01:33.821', 1, '2017-01-01T08:01:33.821', 1);
INSERT INTO code VALUES('1Z', 1, 21, TRUE   , 1, '2017-01-01T08:01:33.821', 1, '2017-01-01T08:01:33.821', 1);

INSERT INTO code VALUES('2R', 2,  1, DEFAULT, 1, '2017-01-01T08:01:33.821', 1, '2017-01-01T08:01:33.821', 1);
INSERT INTO code VALUES('2N', 2,  2, DEFAULT, 1, '2017-01-01T08:01:33.821', 1, '2017-01-01T08:01:33.821', 1);

INSERT INTO code VALUES('3A', 3,  1, DEFAULT, 1, '2017-01-01T08:01:33.821', 1, '2017-01-01T08:01:33.821', 1);
INSERT INTO code VALUES('3B', 3,  2, DEFAULT, 1, '2017-01-01T08:01:33.821', 1, '2017-01-01T08:01:33.821', 1);
INSERT INTO code VALUES('3C', 3,  3, DEFAULT, 1, '2017-01-01T08:01:33.821', 1, '2017-01-01T08:01:33.821', 1);
INSERT INTO code VALUES('3H', 3,  4, DEFAULT, 1, '2017-01-01T08:01:33.821', 1, '2017-01-01T08:01:33.821', 1);
INSERT INTO code VALUES('3D', 3,  5, DEFAULT, 1, '2017-01-01T08:01:33.821', 1, '2017-01-01T08:01:33.821', 1);
INSERT INTO code VALUES('3E', 3,  6, DEFAULT, 1, '2017-01-01T08:01:33.821', 1, '2017-01-01T08:01:33.821', 1);
INSERT INTO code VALUES('3F', 3,  7, DEFAULT, 1, '2017-01-01T08:01:33.821', 1, '2017-01-01T08:01:33.821', 1);
INSERT INTO code VALUES('3G', 3,  8, DEFAULT, 1, '2017-01-01T08:01:33.821', 1, '2017-01-01T08:01:33.821', 1);
INSERT INTO code VALUES('3I', 3,  9, DEFAULT, 1, '2017-01-01T08:01:33.821', 1, '2017-01-01T08:01:33.821', 1);
INSERT INTO code VALUES('3O', 3, 10, DEFAULT, 1, '2017-01-01T08:01:33.821', 1, '2017-01-01T08:01:33.821', 1);
INSERT INTO code VALUES('3K', 3, 11, DEFAULT, 1, '2017-01-01T08:01:33.821', 1, '2017-01-01T08:01:33.821', 1);
INSERT INTO code VALUES('3L', 3, 12, DEFAULT, 1, '2017-01-01T08:01:33.821', 1, '2017-01-01T08:01:33.821', 1);
INSERT INTO code VALUES('3U', 3, 13, TRUE   , 1, '2017-01-01T08:01:33.821', 1, '2017-01-01T08:01:33.821', 1);
INSERT INTO code VALUES('3Z', 3, 14, TRUE   , 1, '2017-01-01T08:01:33.821', 1, '2017-01-01T08:01:33.821', 1);

INSERT INTO code VALUES('4A', 4,  1, DEFAULT, 1, '2017-01-01T08:01:33.821', 1, '2017-01-01T08:01:33.821', 1);
INSERT INTO code VALUES('4B', 4,  2, DEFAULT, 1, '2017-01-01T08:01:33.821', 1, '2017-01-01T08:01:33.821', 1);
INSERT INTO code VALUES('4C', 4,  3, DEFAULT, 1, '2017-01-01T08:01:33.821', 1, '2017-01-01T08:01:33.821', 1);
INSERT INTO code VALUES('4D', 4,  4, DEFAULT, 1, '2017-01-01T08:01:33.821', 1, '2017-01-01T08:01:33.821', 1);
INSERT INTO code VALUES('4E', 4,  5, DEFAULT, 1, '2017-01-01T08:01:33.821', 1, '2017-01-01T08:01:33.821', 1);
INSERT INTO code VALUES('4F', 4,  6, DEFAULT, 1, '2017-01-01T08:01:33.821', 1, '2017-01-01T08:01:33.821', 1);
INSERT INTO code VALUES('4G', 4,  7, DEFAULT, 1, '2017-01-01T08:01:33.821', 1, '2017-01-01T08:01:33.821', 1);
INSERT INTO code VALUES('4H', 4,  8, DEFAULT, 1, '2017-01-01T08:01:33.821', 1, '2017-01-01T08:01:33.821', 1);
INSERT INTO code VALUES('4I', 4,  9, DEFAULT, 1, '2017-01-01T08:01:33.821', 1, '2017-01-01T08:01:33.821', 1);
INSERT INTO code VALUES('4K', 4, 10, DEFAULT, 1, '2017-01-01T08:01:33.821', 1, '2017-01-01T08:01:33.821', 1);
INSERT INTO code VALUES('4M', 4, 11, DEFAULT, 1, '2017-01-01T08:01:33.821', 1, '2017-01-01T08:01:33.821', 1);
INSERT INTO code VALUES('4N', 4, 12, DEFAULT, 1, '2017-01-01T08:01:33.821', 1, '2017-01-01T08:01:33.821', 1);
INSERT INTO code VALUES('4O', 4, 13, DEFAULT, 1, '2017-01-01T08:01:33.821', 1, '2017-01-01T08:01:33.821', 1);
INSERT INTO code VALUES('4L', 4, 14, DEFAULT, 1, '2017-01-01T08:01:33.821', 1, '2017-01-01T08:01:33.821', 1);
INSERT INTO code VALUES('4U', 4, 15, TRUE   , 1, '2017-01-01T08:01:33.821', 1, '2017-01-01T08:01:33.821', 1);
INSERT INTO code VALUES('4X', 4, 16, TRUE   , 1, '2017-01-01T08:01:33.821', 1, '2017-01-01T08:01:33.821', 1);
INSERT INTO code VALUES('4Y', 4, 17, TRUE   , 1, '2017-01-01T08:01:33.821', 1, '2017-01-01T08:01:33.821', 1);
INSERT INTO code VALUES('4Z', 4, 18, TRUE   , 1, '2017-01-01T08:01:33.821', 1, '2017-01-01T08:01:33.821', 1);

INSERT INTO code VALUES('5A', 5,  1, TRUE   , 1, '2017-01-01T08:01:33.821', 1, '2017-01-01T08:01:33.821', 1);
INSERT INTO code VALUES('5B', 5,  2, TRUE   , 1, '2017-01-01T08:01:33.821', 1, '2017-01-01T08:01:33.821', 1);
INSERT INTO code VALUES('5C', 5,  3, TRUE   , 1, '2017-01-01T08:01:33.821', 1, '2017-01-01T08:01:33.821', 1);
INSERT INTO code VALUES('5E', 5,  4, DEFAULT, 1, '2017-01-01T08:01:33.821', 1, '2017-01-01T08:01:33.821', 1);
INSERT INTO code VALUES('5F', 5,  5, DEFAULT, 1, '2017-01-01T08:01:33.821', 1, '2017-01-01T08:01:33.821', 1);
INSERT INTO code VALUES('5G', 5,  6, DEFAULT, 1, '2017-01-01T08:01:33.821', 1, '2017-01-01T08:01:33.821', 1);
INSERT INTO code VALUES('5H', 5,  7, DEFAULT, 1, '2017-01-01T08:01:33.821', 1, '2017-01-01T08:01:33.821', 1);
INSERT INTO code VALUES('5I', 5,  8, DEFAULT, 1, '2017-01-01T08:01:33.821', 1, '2017-01-01T08:01:33.821', 1);
INSERT INTO code VALUES('5M', 5,  9, DEFAULT, 1, '2017-01-01T08:01:33.821', 1, '2017-01-01T08:01:33.821', 1);
INSERT INTO code VALUES('5S', 5, 10, DEFAULT, 1, '2017-01-01T08:01:33.821', 1, '2017-01-01T08:01:33.821', 1);
INSERT INTO code VALUES('5D', 5, 11, TRUE   , 1, '2017-01-01T08:01:33.821', 1, '2017-01-01T08:01:33.821', 1);
INSERT INTO code VALUES('5K', 5, 12, TRUE   , 1, '2017-01-01T08:01:33.821', 1, '2017-01-01T08:01:33.821', 1);
INSERT INTO code VALUES('5U', 5, 13, DEFAULT, 1, '2017-01-01T08:01:33.821', 1, '2017-01-01T08:01:33.821', 1);

INSERT INTO code VALUES('6M', 6,  1, DEFAULT, 1, '2017-01-01T08:01:33.821', 1, '2017-01-01T08:01:33.821', 1);
INSERT INTO code VALUES('6T', 6,  2, DEFAULT, 1, '2017-01-01T08:01:33.821', 1, '2017-01-01T08:01:33.821', 1);
INSERT INTO code VALUES('6O', 6,  3, DEFAULT, 1, '2017-01-01T08:01:33.821', 1, '2017-01-01T08:01:33.821', 1);
INSERT INTO code VALUES('6P', 6,  4, TRUE   , 1, '2017-01-01T08:01:33.821', 1, '2017-01-01T08:01:33.821', 1);
INSERT INTO code VALUES('6Z', 6,  5, TRUE   , 1, '2017-01-01T08:01:33.821', 1, '2017-01-01T08:01:33.821', 1);

INSERT INTO code VALUES('7K', 7,  1, DEFAULT, 1, '2017-01-01T08:01:33.821', 1, '2017-01-01T08:01:33.821', 1);
INSERT INTO code VALUES('7L', 7,  2, DEFAULT, 1, '2017-01-01T08:01:33.821', 1, '2017-01-01T08:01:33.821', 1);
INSERT INTO code VALUES('7M', 7,  3, TRUE   , 1, '2017-01-01T08:01:33.821', 1, '2017-01-01T08:01:33.821', 1);
INSERT INTO code VALUES('7Z', 7,  4, TRUE   , 1, '2017-01-01T08:01:33.821', 1, '2017-01-01T08:01:33.821', 1);

INSERT INTO code VALUES('8I', 8,  1, DEFAULT, 1, '2017-01-01T08:01:33.821', 1, '2017-01-01T08:01:33.821', 1);
INSERT INTO code VALUES('8O', 8,  2, DEFAULT, 1, '2017-01-01T08:01:33.821', 1, '2017-01-01T08:01:33.821', 1);
INSERT INTO code VALUES('8P', 8,  3, DEFAULT, 1, '2017-01-01T08:01:33.821', 1, '2017-01-01T08:01:33.821', 1);
INSERT INTO code VALUES('8W', 8,  4, DEFAULT, 1, '2017-01-01T08:01:33.821', 1, '2017-01-01T08:01:33.821', 1);
INSERT INTO code VALUES('8Z', 8,  5, TRUE   , 1, '2017-01-01T08:01:33.821', 1, '2017-01-01T08:01:33.821', 1);


INSERT INTO code_tr VALUES(DEFAULT, '1F', 'de', 'Feinstaub, Partikel', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '1A', 'de', 'Ozon, Oxidantien', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '1B', 'de', 'Stickoxide, Ammoniak', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '1C', 'de', 'Kohlenwasserstoffe, nicht chloriert, VOC', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '1D', 'de', 'Kohlenmonoxid', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '1E', 'de', 'SO2, Schwefelverbindungen,', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '1G', 'de', 'Metalle', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '1H', 'de', 'Halogene, halogenierte Stoffe', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '1I', 'de', 'Saure Aerosole', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '1K', 'de', 'Radioaktive Stoffe', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '1L', 'de', 'Asbest, Fasern', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '1M', 'de', 'Tabakrauch, Passivrauchen', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '1N', 'de', 'Keine Messung, andere Art der Exposure (Stadt : Land) z.B. Lärm', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '1P', 'de', 'Pollen', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '1R', 'de', 'Feuchtigkeit in der Raumluft', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '1S', 'de', 'Milben, Allergene in den Raumluft', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '1T', 'de', 'Temperatur', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '1U', 'de', 'Andere / Übrige', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '1V', 'de', 'Verkehr', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '1Y', 'de', 'Gerüche', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '1Z', 'de', 'Mehr als 8 Schadstoffe, alle gemeinsam', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);

INSERT INTO code_tr VALUES(DEFAULT, '2R', 'de', 'Europa', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '2N', 'de', 'Übrige Länder', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);

INSERT INTO code_tr VALUES(DEFAULT, '3A', 'de', 'Säuglinge, Vorschulkinder', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '3B', 'de', 'Schulkinder und Jugendliche', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '3C', 'de', 'Erwachsene (alle)', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '3H', 'de', 'Betagte Personen (65+ Jahre)', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '3D', 'de', 'Personen mit Asthma oder Atemwegsallergie', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '3E', 'de', 'Pers. mit anderer chronischer Lungenkrankheit, COPD', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '3F', 'de', 'Registerdaten, Patienten', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '3G', 'de', 'Schwangere Frauen', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '3I', 'de', 'Sportler/innen', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '3O', 'de', 'Beruflich Exponierte', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '3K', 'de', 'Gewebe', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '3L', 'de', 'Zellen', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '3U', 'de', 'Übrige / Andere', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '3Z', 'de', 'Mehr als 8 Teilnehmergruppen / alle', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);

INSERT INTO code_tr VALUES(DEFAULT, '4A', 'de', 'Sterblichkeit', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '4B', 'de', 'Lungenfunktion', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '4C', 'de', 'Symptome', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '4D', 'de', 'Biochemische oder zelluläre Veränderungen', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '4E', 'de', 'Atemwegskrankheiten akut', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '4F', 'de', 'Atemwegskrankheiten chronisch', 'wie COPD/Asthma', DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '4G', 'de', 'Krebs', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '4H', 'de', 'Herz, Kreislauf, Blut', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '4I', 'de', 'Gehirn, Nerven, Augen, Ohren', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '4K', 'de', 'Belästigung, psychische Folgen, Lebensqualität', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '4M', 'de', 'Medikamentenkonsum, Konsultation, Spitaleintritt', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '4N', 'de', 'Fertilität, Schwangerschaftsproblem, Abort', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '4O', 'de', 'Frühgeburt, Säuglingsgewicht, pränatale Entwicklung', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '4L', 'de', 'Missbildungen', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '4U', 'de', 'Übrige / Andere', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '4X', 'de', 'Kosten', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '4Y', 'de', 'Absenzen, eingeschränkte Aktivität', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '4Z', 'de', 'Mehr als 8 ges. Zielgrössen / Alle', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);

INSERT INTO code_tr VALUES(DEFAULT, '5A', 'de', 'Experimentelle Studie unter Belastung / Arbeit', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '5B', 'de', 'Experimentelle Studie in Ruhe', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '5C', 'de', 'Experimentelle Studie Zellstudie etc.', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '5E', 'de', 'Einmalige Exposition, Unfall, Brand', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '5F', 'de', 'Zeitreihen, Panel, kurzfristige Längsstudie', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '5G', 'de', 'Querschnitt, Fall-Kontrollstudie, deskriptiv', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '5H', 'de', 'Kohortenstudie', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '5I', 'de', 'Interventionsstudie', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '5M', 'de', 'Messstudie, Studienmethodik', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '5S', 'de', 'Statistik', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '5D', 'de', 'Einzelfallbeschreibung, Fallstudie', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '5K', 'de', 'Krankheitsbeschreibung', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '5U', 'de', 'Übersichten, Metaanalysen, HIA', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);

INSERT INTO code_tr VALUES(DEFAULT, '6M', 'de', 'Mensch', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '6T', 'de', 'Tier', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '6O', 'de', 'Viren, Bakterien, Einzeller', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '6P', 'de', 'Pflanzen', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '6Z', 'de', 'Alle / allg. Übersichten', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);

INSERT INTO code_tr VALUES(DEFAULT, '7K', 'de', 'Kurzfristig', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '7L', 'de', 'Langfristig', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '7M', 'de', 'Mittelfristig', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '7Z', 'de', 'Alle', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);

INSERT INTO code_tr VALUES(DEFAULT, '8I', 'de', 'Raumluft', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '8O', 'de', 'Aussenluft', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '8P', 'de', 'Individuelle Messung', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '8W', 'de', 'Berufliche Exposition', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '8Z', 'de', 'Alle', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);


INSERT INTO code_tr VALUES(DEFAULT, '1F', 'en', 'Particles, Particulate Matter', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '1A', 'en', 'Ozone, Oxidants', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '1B', 'en', 'Nitrogen Oxides, Ammonia', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '1C', 'en', 'Hydrocarbons, non-chlorinated, VOC', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '1D', 'en', 'Carbonmonoxide', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '1E', 'en', 'SO2, sulfur compounds', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '1G', 'en', 'Metals', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '1H', 'en', 'Halogens, halogenated substances', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '1I', 'en', 'Acidic Aerosols', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '1K', 'en', 'Radioactive substances', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '1L', 'en', 'Asbestos, fibres', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '1M', 'en', 'Tobacco smoke, passive smoking', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '1N', 'en', 'Different exposure or assessment (geographic, noise)', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '1P', 'en', 'Pollen', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '1R', 'en', 'Indoor air humidity', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '1S', 'en', 'Mites, indoor allergens', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '1T', 'en', 'Temperature', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '1U', 'en', 'Others', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '1V', 'en', 'Traffic', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '1Y', 'en', 'Odours', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '1Z', 'en', 'More than 8 pollutants, all together', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);

INSERT INTO code_tr VALUES(DEFAULT, '2R', 'en', 'Europe', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '2N', 'en', 'Other countries', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);

INSERT INTO code_tr VALUES(DEFAULT, '3A', 'en', 'Newborns, infants, pre-school children', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '3B', 'en', 'School children, adolescents', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '3C', 'en', 'Adults (19+)', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '3H', 'en', 'Agend persons (65+)', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '3D', 'en', 'People with asthma or respiratory allergies', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '3E', 'en', 'People with chronic respiratory disease, COPD', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '3F', 'en', 'Registry data, patient records', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '3G', 'en', 'Pregnant women', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '3I', 'en', 'Athletes', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '3O', 'en', 'Ocupationally exposed', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '3K', 'en', 'Tissue', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '3L', 'en', 'Cells', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '3U', 'en', 'Others', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '3Z', 'en', 'More than 8 participant groups / all', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);

INSERT INTO code_tr VALUES(DEFAULT, '4A', 'en', 'Mortality', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '4B', 'en', 'Lung function, pulmonary function', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '4C', 'en', 'Symptoms', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '4D', 'en', 'Biochemical or cellular responses', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '4E', 'en', 'Respiratory diseases acute', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '4F', 'en', 'Respiratory diseases chronic', 'like COPD/Asthma', DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '4G', 'en', 'Cancer', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '4H', 'en', 'Heart, cardovascular system, blood', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '4I', 'en', 'Brain, nervous system, eyes, ears', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '4K', 'en', 'Annoyance, well-being, quality of life', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '4M', 'en', 'Drug intake, consultation, hospital admission', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '4N', 'en', 'Fertility, pregnancy complications, miscarriage', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '4O', 'en', 'Preterm birth, birth weight, prenatal development', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '4L', 'en', 'Congenital malformation', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '4U', 'en', 'Others', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '4X', 'en', 'Costs', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '4Y', 'en', 'Absenteeism, restricted activity', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '4Z', 'en', 'More than 8 health outcomes / all', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);

INSERT INTO code_tr VALUES(DEFAULT, '5A', 'en', 'Experimental study under exercising conditions', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '5B', 'en', 'Experimental study under resting conditions', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '5C', 'en', 'Experimental study with cells, tissues', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '5E', 'en', 'Accidental release, fire', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '5F', 'en', 'Panel study,  time series', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '5G', 'en', 'Cross-sectional or case-control study, descriptive', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '5H', 'en', 'Cohort Study', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '5I', 'en', 'Intervention', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '5M', 'en', 'Methodological study, Exposure assessment, modelling', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '5S', 'en', 'Statistics', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '5D', 'en', 'Case study', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '5U', 'en', 'Review, meta-analysis', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);

INSERT INTO code_tr VALUES(DEFAULT, '6M', 'en', 'Humans', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '6T', 'en', 'Animals', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '6O', 'en', 'Viruses, Bacteria, Protozoa', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '6P', 'en', 'Plants', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '6Z', 'en', 'All / General Overviews', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);

INSERT INTO code_tr VALUES(DEFAULT, '7K', 'en', 'Short-term', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '7L', 'en', 'Long-term', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '7M', 'en', 'Mid-term', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '7Z', 'en', 'All', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);

INSERT INTO code_tr VALUES(DEFAULT, '8I', 'en', 'Indoor Air', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '8O', 'en', 'Ambient air', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '8P', 'en', 'Personal measurement', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '8W', 'en', 'Occupational exposure', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '8Z', 'en', 'All', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);


INSERT INTO code_tr VALUES(DEFAULT, '1F', 'fr', 'Poussière fines, particules', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '1A', 'fr', 'Ozone, Oxydants', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '1B', 'fr', 'Oxydes d''azote, ammoniac', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '1C', 'fr', 'Hydrocarbures non-chlorurés', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '1D', 'fr', 'Monoxyde de carbone', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '1E', 'fr', 'SO2, composé de soufre', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '1G', 'fr', 'Métals', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '1H', 'fr', 'Halogènes, substances halogénées', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '1I', 'fr', 'Aérosols acides', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '1K', 'fr', 'Substances radioactives', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '1L', 'fr', 'Amiante, fibres', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '1M', 'fr', 'Tabagisme passif, fumée de cigarette', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '1P', 'fr', 'Pollen', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '1R', 'fr', 'Humidité (air intérieur)', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '1S', 'fr', 'Allergènes dans l''air intérieur', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '1T', 'fr', 'Température', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '1U', 'fr', 'Autres', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '1V', 'fr', 'Trafic / circulation', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '1Y', 'fr', 'Odeur', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '1Z', 'fr', 'Plus de 8 polluants / tous', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);

INSERT INTO code_tr VALUES(DEFAULT, '2R', 'fr', 'Europe', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '2N', 'fr', 'Autres pays', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);

INSERT INTO code_tr VALUES(DEFAULT, '3A', 'fr', 'Nourisson, infants, enfants préscolaires', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '3B', 'fr', 'Enfants scolaires, adolescents', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '3C', 'fr', 'Adultes (19+)', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '3H', 'fr', 'Personnes agées (65+)', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '3D', 'fr', 'Personnes asthmatiques ou allérgiques', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '3E', 'fr', 'Pers. souffrantes des maladies pulmonaire chronique', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '3F', 'fr', 'Données de registre ou des patients', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '3G', 'fr', 'Femmes enceintes', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '3I', 'fr', 'Sportifs', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '3O', 'fr', 'Personnes exposées au travail', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '3K', 'fr', 'Tissus', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '3L', 'fr', 'Cellules', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '3U', 'fr', 'Autres', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '3Z', 'fr', 'Plus de 8 / tous', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);

INSERT INTO code_tr VALUES(DEFAULT, '4A', 'fr', 'Mortalité', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '4B', 'fr', 'Fonction pulmonaire', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '4C', 'fr', 'Symptômes, Signes', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '4D', 'fr', 'Changements biochimiques ou cellulaire', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '4E', 'fr', 'Maladie respiratoire, imminante', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '4F', 'fr', 'Maladie respiratoire, chronique', 'comme COPD/Asthma', DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '4G', 'fr', 'Cancer', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '4H', 'fr', 'Coeur, circulation, sang', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '4I', 'fr', 'Système nerveux, yeux, oreilles', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '4K', 'fr', 'Nuisance, bien-être, qualité de vie', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '4M', 'fr', 'Médicaments, visite médicale, hospitalisation', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '4N', 'fr', 'Fertilité, complication de grossesse, fausse couche', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '4O', 'fr', 'Naissance prématurée, poids de naissance ', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '4L', 'fr', 'Malformation', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '4U', 'fr', 'Autres', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '4X', 'fr', 'Frais / coûts', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '4Y', 'fr', 'Absentéisme, activités réduites', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '4Z', 'fr', 'Plus de 8 effets / tous', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);

INSERT INTO code_tr VALUES(DEFAULT, '5A', 'fr', 'Etude expérimentale dans des conditions exercicantes', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '5B', 'fr', 'Etude expérimentale dans des conditions sédentaires', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '5C', 'fr', 'Etude expérimentale avec cellules etc.', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '5E', 'fr', 'Accident, incident chimique, feu', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '5F', 'fr', 'Etude panel, étude longitudinale à court terme, séries chronologiques', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '5G', 'fr', 'Etude transversal ou cas-témoin, descriptive', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '5H', 'fr', 'Etude de cohorte', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '5I', 'fr', 'Intervention', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '5M', 'fr', 'Méthodologie', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '5S', 'fr', 'Statistique ', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '5D', 'fr', 'Étude de cas', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '5U', 'fr', 'Review, révue, méta-analyse', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);

INSERT INTO code_tr VALUES(DEFAULT, '6M', 'fr', 'Hommes', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '6T', 'fr', 'Animaux', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '6O', 'fr', 'Virus, Bactéries, Protozoaires', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '6P', 'fr', 'Plantes', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '6Z', 'fr', 'Tous / Exposés gen.', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);

INSERT INTO code_tr VALUES(DEFAULT, '7K', 'fr', 'à court terme', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '7L', 'fr', 'à long terme', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '7M', 'fr', 'à moyen terme', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '7Z', 'fr', 'tous', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);

INSERT INTO code_tr VALUES(DEFAULT, '8I', 'fr', 'Air intérieur', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '8O', 'fr', 'Air extérieur', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '8P', 'fr', 'Mesures personalisées', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '8W', 'fr', 'Exposition lié au travail', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO code_tr VALUES(DEFAULT, '8Z', 'fr', 'Tous', null, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);

select setval('code_tr_id_seq', max(id)) FROM code_tr;


INSERT INTO scipamato_user(id, user_name, first_name, last_name, email, password, enabled, version, created, created_by, last_modified, last_modified_by) VALUES
  (1, 'testuser', 'user', 'test', 'testuser@scipamato.org', '$2a$04$ENEpFnWzYVveVg3FPdkDdeucUwdVn4nxu4IP2Zj1bFXiPvLQED6.C', TRUE, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT),
  (2, 'admin', 'admin', 'admin', 'admin@scipamato.org', '$2a$04$oOL75tgCf3kXdr6vO5gagu6sIUZWfXyEhZHmDd4LpGvOPTaO5xEoO', TRUE, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT),
  (3, 'mkj', 'm', 'k j', 'mkj@scipamato.org', '$2a$04$9n.7Iv3eBNU6gqq5cOg8X.QRFBrDbzUOW/wBq5KdHKjOeVt4r0jwG', TRUE, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT),
  (4, 'rk', 'r', 'k', 'rk@scipamato.org', '$2a$04$UrFcx9Rqadw5JKkJwDpF8unmfubbgna8IZT6FsqW0uEoSd8kMs8.6', TRUE, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT),
  (5, 'rr', 'r', 'r', 'rr@scipamato.org', '$2a$04$HbvKICm3qVe/WVqG7I5j9ObL90s3GCpPzSYWPRQ8nGkxVedGYC5Q.', FALSE, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT),
  (6, 'dyntar', 'd', 'd', 'dyntar@scipamato.org', '$2a$04$PW.Pr11mwKSwOKdzrN/S6ed2MC3.UjaaH56GDN4xoI8nrwso8RSmC', FALSE, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT),
  (7, 'soenja', 'soenja', 'soenja', 'soenja@scipamato.org', '$2a$04$jecBl48WyfUxRLkShuyZqOUfkiuVuAi1O6Kus8ij8uBWtLuIGzW8S', FALSE, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT),
  (8, 'ml', 'ml', 'ml', 'ml@scipamato.org', '$2a$04$8i/0iR8iYpznrVR69LCM1ewT9J0CNBGiQ..fAWxy/wiAjP66a/1oe', FALSE, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);

select setval('scipamato_user_id_seq', max(id)) FROM scipamato_user;


INSERT INTO user_role(id, user_id, role_id, version, created, created_by, last_modified, last_modified_by) VALUES
  (1, 1, 2, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT),
  (2, 2, 1, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT),
  (3, 3, 1, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT),
  (4, 3, 2, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT),
  (5, 4, 1, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT),
  (6, 4, 2, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT),
  (7, 5, 2, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT),
  (8, 6, 2, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);

select setval('user_role_id_seq', max(id)) FROM user_role;