package ch.difty.scipamato.common.persistence;

import static org.assertj.core.api.Assertions.assertThat;

import org.junit.Test;

public class SortMapperTest {

    // The SortMapper Test depends on a table generated by jOOQ. We don't have one
    // in this module.
    // You can find the test in scipamato-core-persitence-jooq as
    // ch.difty.scipamato.common.common.common.persistence.SortMapperTest
    // coverage is 100%

    @Test
    public void dummyTest() {
        assertThat(true).isTrue();
    }

}
