name: Check

on:
  push:
    branches:
    - main
    tags:
    - '*'

  pull_request:
    branches:
    - main

permissions:
  security-events: write
  contents: read

jobs:
  build:
    strategy:
      matrix:
        jdk: [21]
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

    - name: Gradle wrapper validation
      uses: gradle/actions/wrapper-validation@50e97c2cd7a37755bbfafc9c5b7cafaece252f6e # v6
      
    - name: Set up JDK ${{ matrix.jdk }}
      uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5
      with:
        distribution: 'zulu'
        java-version: ${{ matrix.jdk }}

    - name: Gradle cache
      uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: gradle-${{ runner.os }}-${{ hashFiles('**/gradle-wrapper.properties', '**/*.gradle*', '**/*.versions.toml') }}-${{ hashFiles('**/*.kts') }}
        restore-keys: |
          gradle-${{ runner.os }}-${{ hashFiles('**/gradle-wrapper.properties', '**/*.gradle*', '**/*.versions.toml') }}-
          gradle-${{ runner.os }}-

    - name: Login to Docker Hub
      uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Download postgres
      run: docker pull postgres:15.4

    - name: Run build
      run:  ./gradlew check detekt mergeDetektSarif :gradle-plugins:buildPlugins --no-daemon --warning-mode=all --continue

    - name: Upload failure artifacts
      if: failure()
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
      with:
        name: reports
        path: '**/build/reports'

    - name: Upload sarif file to GitHub
      uses: github/codeql-action/upload-sarif@95e58e9a2cdfd71adc6e0353d5c52f41a045d225 # v4
      if: success() || failure()
      with:
        sarif_file: build/detekt-merged.sarif
        category: detekt

